// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package update_task_status_after_train

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgres creates a new instance of MockPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgres {
	mock := &MockPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgres is an autogenerated mock type for the Postgres type
type MockPostgres struct {
	mock.Mock
}

type MockPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgres) EXPECT() *MockPostgres_Expecter {
	return &MockPostgres_Expecter{mock: &_m.Mock}
}

// UpdateTaskStatusByID provides a mock function for the type MockPostgres
func (_mock *MockPostgres) UpdateTaskStatusByID(ctx context.Context, id uuid.UUID, status string, oldStatus string) error {
	ret := _mock.Called(ctx, id, status, oldStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskStatusByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, id, status, oldStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_UpdateTaskStatusByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskStatusByID'
type MockPostgres_UpdateTaskStatusByID_Call struct {
	*mock.Call
}

// UpdateTaskStatusByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status string
//   - oldStatus string
func (_e *MockPostgres_Expecter) UpdateTaskStatusByID(ctx interface{}, id interface{}, status interface{}, oldStatus interface{}) *MockPostgres_UpdateTaskStatusByID_Call {
	return &MockPostgres_UpdateTaskStatusByID_Call{Call: _e.mock.On("UpdateTaskStatusByID", ctx, id, status, oldStatus)}
}

func (_c *MockPostgres_UpdateTaskStatusByID_Call) Run(run func(ctx context.Context, id uuid.UUID, status string, oldStatus string)) *MockPostgres_UpdateTaskStatusByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPostgres_UpdateTaskStatusByID_Call) Return(err error) *MockPostgres_UpdateTaskStatusByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_UpdateTaskStatusByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status string, oldStatus string) error) *MockPostgres_UpdateTaskStatusByID_Call {
	_c.Call.Return(run)
	return _c
}
