// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package outbox

import (
	"context"
	"sync"

	"github.com/AridanWarlock/pinnAutomizer/tasks/internal/domain"
	"github.com/AridanWarlock/pinnAutomizer/pkg/core"
	"github.com/google/uuid"
)

// Ensure that MockPostgres does implement Postgres.
// If this is not the case, regenerate this file with mockery.
var _ Postgres = &MockPostgres{}

// MockPostgres is a mock implementation of Postgres.
//
//	func TestSomethingThatUsesPostgres(t *testing.T) {
//
//		// make and configure a mocked Postgres
//		mockedPostgres := &MockPostgres{
//			DeleteEventsByIDsFunc: func(ctx context.Context, ids []uuid.UUID) error {
//				panic("mock out the DeleteEventsByIDs method")
//			},
//			GetAvailableEventsFunc: func(ctx context.Context, batchSize int) ([]domain.Event, error) {
//				panic("mock out the GetAvailableEvents method")
//			},
//			InTransactionFunc: func(ctx context.Context, inTx func(ctx context.Context) error) error {
//				panic("mock out the InTransaction method")
//			},
//		}
//
//		// use mockedPostgres in code that requires Postgres
//		// and then make assertions.
//
//	}
type MockPostgres struct {
	// DeleteEventsByIDsFunc mocks the DeleteEventsByIDs method.
	DeleteEventsByIDsFunc func(ctx context.Context, ids []uuid.UUID) error

	// GetAvailableEventsFunc mocks the GetAvailableEvents method.
	GetAvailableEventsFunc func(ctx context.Context, batchSize int) ([]domain.Event, error)

	// InTransactionFunc mocks the InTransaction method.
	InTransactionFunc func(ctx context.Context, inTx func(ctx context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteEventsByIDs holds details about calls to the DeleteEventsByIDs method.
		DeleteEventsByIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ids is the ids argument value.
			Ids []uuid.UUID
		}
		// GetAvailableEvents holds details about calls to the GetAvailableEvents method.
		GetAvailableEvents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BatchSize is the batchSize argument value.
			BatchSize int
		}
		// InTransaction holds details about calls to the InTransaction method.
		InTransaction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InTx is the inTx argument value.
			InTx func(ctx context.Context) error
		}
	}
	lockDeleteEventsByIDs  sync.RWMutex
	lockGetAvailableEvents sync.RWMutex
	lockInTransaction      sync.RWMutex
}

// DeleteEventsByIDs calls DeleteEventsByIDsFunc.
func (mock *MockPostgres) DeleteEventsByIdKeys(ctx context.Context, ids []uuid.UUID) error {
	if mock.DeleteEventsByIDsFunc == nil {
		panic("MockPostgres.DeleteEventsByIDsFunc: method is nil but Postgres.DeleteEventsByIDs was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ids []uuid.UUID
	}{
		Ctx: ctx,
		Ids: ids,
	}
	mock.lockDeleteEventsByIDs.Lock()
	mock.calls.DeleteEventsByIDs = append(mock.calls.DeleteEventsByIDs, callInfo)
	mock.lockDeleteEventsByIDs.Unlock()
	return mock.DeleteEventsByIDsFunc(ctx, ids)
}

// DeleteEventsByIDsCalls gets all the calls that were made to DeleteEventsByIDs.
// Check the length with:
//
//	len(mockedPostgres.DeleteEventsByIDsCalls())
func (mock *MockPostgres) DeleteEventsByIDsCalls() []struct {
	Ctx context.Context
	Ids []uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		Ids []uuid.UUID
	}
	mock.lockDeleteEventsByIDs.RLock()
	calls = mock.calls.DeleteEventsByIDs
	mock.lockDeleteEventsByIDs.RUnlock()
	return calls
}

// GetAvailableEvents calls GetAvailableEventsFunc.
func (mock *MockPostgres) GetAvailableEvents(ctx context.Context, batchSize int) ([]domain.Event, error) {
	if mock.GetAvailableEventsFunc == nil {
		panic("MockPostgres.GetAvailableEventsFunc: method is nil but Postgres.GetAvailableEvents was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		BatchSize int
	}{
		Ctx:       ctx,
		BatchSize: batchSize,
	}
	mock.lockGetAvailableEvents.Lock()
	mock.calls.GetAvailableEvents = append(mock.calls.GetAvailableEvents, callInfo)
	mock.lockGetAvailableEvents.Unlock()
	return mock.GetAvailableEventsFunc(ctx, batchSize)
}

// GetAvailableEventsCalls gets all the calls that were made to GetAvailableEvents.
// Check the length with:
//
//	len(mockedPostgres.GetAvailableEventsCalls())
func (mock *MockPostgres) GetAvailableEventsCalls() []struct {
	Ctx       context.Context
	BatchSize int
} {
	var calls []struct {
		Ctx       context.Context
		BatchSize int
	}
	mock.lockGetAvailableEvents.RLock()
	calls = mock.calls.GetAvailableEvents
	mock.lockGetAvailableEvents.RUnlock()
	return calls
}

// InTransaction calls InTransactionFunc.
func (mock *MockPostgres) InTransaction(ctx context.Context, inTx func(ctx context.Context) error) error {
	if mock.InTransactionFunc == nil {
		panic("MockPostgres.InTransactionFunc: method is nil but Postgres.InTransaction was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		InTx func(ctx context.Context) error
	}{
		Ctx:  ctx,
		InTx: inTx,
	}
	mock.lockInTransaction.Lock()
	mock.calls.InTransaction = append(mock.calls.InTransaction, callInfo)
	mock.lockInTransaction.Unlock()
	return mock.InTransactionFunc(ctx, inTx)
}

// InTransactionCalls gets all the calls that were made to InTransaction.
// Check the length with:
//
//	len(mockedPostgres.InTransactionCalls())
func (mock *MockPostgres) InTransactionCalls() []struct {
	Ctx  context.Context
	InTx func(ctx context.Context) error
} {
	var calls []struct {
		Ctx  context.Context
		InTx func(ctx context.Context) error
	}
	mock.lockInTransaction.RLock()
	calls = mock.calls.InTransaction
	mock.lockInTransaction.RUnlock()
	return calls
}

// Ensure that MockWriter does implement Writer.
// If this is not the case, regenerate this file with mockery.
var _ Writer = &MockWriter{}

// MockWriter is a mock implementation of Writer.
//
//	func TestSomethingThatUsesWriter(t *testing.T) {
//
//		// make and configure a mocked Writer
//		mockedWriter := &MockWriter{
//			WriteMessagesFunc: func(ctx context.Context, msgs ...core.KafkaMessage) error {
//				panic("mock out the WriteMessages method")
//			},
//		}
//
//		// use mockedWriter in code that requires Writer
//		// and then make assertions.
//
//	}
type MockWriter struct {
	// WriteMessagesFunc mocks the WriteMessages method.
	WriteMessagesFunc func(ctx context.Context, msgs ...core.KafkaMessage) error

	// calls tracks calls to the methods.
	calls struct {
		// WriteMessages holds details about calls to the WriteMessages method.
		WriteMessages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msgs is the msgs argument value.
			Msgs []core.KafkaMessage
		}
	}
	lockWriteMessages sync.RWMutex
}

// WriteMessages calls WriteMessagesFunc.
func (mock *MockWriter) WriteMessages(ctx context.Context, msgs ...core.KafkaMessage) error {
	if mock.WriteMessagesFunc == nil {
		panic("MockWriter.WriteMessagesFunc: method is nil but Writer.WriteMessages was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Msgs []core.KafkaMessage
	}{
		Ctx:  ctx,
		Msgs: msgs,
	}
	mock.lockWriteMessages.Lock()
	mock.calls.WriteMessages = append(mock.calls.WriteMessages, callInfo)
	mock.lockWriteMessages.Unlock()
	return mock.WriteMessagesFunc(ctx, msgs...)
}

// WriteMessagesCalls gets all the calls that were made to WriteMessages.
// Check the length with:
//
//	len(mockedWriter.WriteMessagesCalls())
func (mock *MockWriter) WriteMessagesCalls() []struct {
	Ctx  context.Context
	Msgs []core.KafkaMessage
} {
	var calls []struct {
		Ctx  context.Context
		Msgs []core.KafkaMessage
	}
	mock.lockWriteMessages.RLock()
	calls = mock.calls.WriteMessages
	mock.lockWriteMessages.RUnlock()
	return calls
}
