// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package httpin

import (
	"sync"
)

// Ensure that mockvalidatable does implement validatable.
// If this is not the case, regenerate this file with mockery.
var _ validatable = &mockvalidatable{}

// mockvalidatable is a mock implementation of validatable.
//
//	func TestSomethingThatUsesvalidatable(t *testing.T) {
//
//		// make and configure a mocked validatable
//		mockedvalidatable := &mockvalidatable{
//			ValidateFunc: func() error {
//				panic("mock out the Validate method")
//			},
//		}
//
//		// use mockedvalidatable in code that requires validatable
//		// and then make assertions.
//
//	}
type mockvalidatable struct {
	// ValidateFunc mocks the Validate method.
	ValidateFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// Validate holds details about calls to the Validate method.
		Validate []struct {
		}
	}
	lockValidate sync.RWMutex
}

// Validate calls ValidateFunc.
func (mock *mockvalidatable) Validate() error {
	if mock.ValidateFunc == nil {
		panic("mockvalidatable.ValidateFunc: method is nil but validatable.Validate was just called")
	}
	callInfo := struct {
	}{}
	mock.lockValidate.Lock()
	mock.calls.Validate = append(mock.calls.Validate, callInfo)
	mock.lockValidate.Unlock()
	return mock.ValidateFunc()
}

// ValidateCalls gets all the calls that were made to Validate.
// Check the length with:
//
//	len(mockedvalidatable.ValidateCalls())
func (mock *mockvalidatable) ValidateCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockValidate.RLock()
	calls = mock.calls.Validate
	mock.lockValidate.RUnlock()
	return calls
}
