// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package authLogin

import (
	"context"
	"sync"
	"time"

	"github.com/AridanWarlock/pinnAutomizer/auth/internal/domain"
	"github.com/AridanWarlock/pinnAutomizer/pkg/core"
	"github.com/google/uuid"
)

// Ensure that MockUsecase does implement Usecase.
// If this is not the case, regenerate this file with mockery.
var _ Usecase = &MockUsecase{}

// MockUsecase is a mock implementation of Usecase.
//
//	func TestSomethingThatUsesUsecase(t *testing.T) {
//
//		// make and configure a mocked Usecase
//		mockedUsecase := &MockUsecase{
//			LoginFunc: func(ctx context.Context, in Input) (Output, error) {
//				panic("mock out the Login method")
//			},
//		}
//
//		// use mockedUsecase in code that requires Usecase
//		// and then make assertions.
//
//	}
type MockUsecase struct {
	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, in Input) (Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In Input
		}
	}
	lockLogin sync.RWMutex
}

// Login calls LoginFunc.
func (mock *MockUsecase) Login(ctx context.Context, in Input) (Output, error) {
	if mock.LoginFunc == nil {
		panic("MockUsecase.LoginFunc: method is nil but Usecase.Login was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  Input
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, in)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedUsecase.LoginCalls())
func (mock *MockUsecase) LoginCalls() []struct {
	Ctx context.Context
	In  Input
} {
	var calls []struct {
		Ctx context.Context
		In  Input
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// Ensure that MockPostgres does implement Postgres.
// If this is not the case, regenerate this file with mockery.
var _ Postgres = &MockPostgres{}

// MockPostgres is a mock implementation of Postgres.
//
//	func TestSomethingThatUsesPostgres(t *testing.T) {
//
//		// make and configure a mocked Postgres
//		mockedPostgres := &MockPostgres{
//			GetJtiByFingerprintFunc: func(ctx context.Context, userID uuid.UUID, fingerprint core.Fingerprint) (core.Jti, error) {
//				panic("mock out the GetJtiByFingerprint method")
//			},
//			GetRolesByUserIDFunc: func(ctx context.Context, userID uuid.UUID) ([]core.Role, error) {
//				panic("mock out the GetRolesByUserID method")
//			},
//			GetUserByLoginFunc: func(ctx context.Context, login string) (domain.User, error) {
//				panic("mock out the GetUserByLogin method")
//			},
//			LoginFunc: func(ctx context.Context, token domain.RefreshToken) (domain.RefreshToken, error) {
//				panic("mock out the Login method")
//			},
//		}
//
//		// use mockedPostgres in code that requires Postgres
//		// and then make assertions.
//
//	}
type MockPostgres struct {
	// GetJtiByFingerprintFunc mocks the GetJtiByFingerprint method.
	GetJtiByFingerprintFunc func(ctx context.Context, userID uuid.UUID, fingerprint core.Fingerprint) (core.Jti, error)

	// GetRolesByUserIDFunc mocks the GetRolesByUserID method.
	GetRolesByUserIDFunc func(ctx context.Context, userID uuid.UUID) ([]core.Role, error)

	// GetUserByLoginFunc mocks the GetUserByLogin method.
	GetUserByLoginFunc func(ctx context.Context, login string) (domain.User, error)

	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, token domain.RefreshToken) (domain.RefreshToken, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetJtiByFingerprint holds details about calls to the GetJtiByFingerprint method.
		GetJtiByFingerprint []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Fingerprint is the fingerprint argument value.
			Fingerprint core.Fingerprint
		}
		// GetRolesByUserID holds details about calls to the GetRolesByUserID method.
		GetRolesByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetUserByLogin holds details about calls to the GetUserByLogin method.
		GetUserByLogin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Login is the login argument value.
			Login string
		}
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token domain.RefreshToken
		}
	}
	lockGetJtiByFingerprint sync.RWMutex
	lockGetRolesByUserID    sync.RWMutex
	lockGetUserByLogin      sync.RWMutex
	lockLogin               sync.RWMutex
}

// GetJtiByFingerprint calls GetJtiByFingerprintFunc.
func (mock *MockPostgres) GetJtiByFingerprint(ctx context.Context, userID uuid.UUID, fingerprint core.Fingerprint) (core.Jti, error) {
	if mock.GetJtiByFingerprintFunc == nil {
		panic("MockPostgres.GetJtiByFingerprintFunc: method is nil but Postgres.GetJtiByFingerprint was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		UserID      uuid.UUID
		Fingerprint core.Fingerprint
	}{
		Ctx:         ctx,
		UserID:      userID,
		Fingerprint: fingerprint,
	}
	mock.lockGetJtiByFingerprint.Lock()
	mock.calls.GetJtiByFingerprint = append(mock.calls.GetJtiByFingerprint, callInfo)
	mock.lockGetJtiByFingerprint.Unlock()
	return mock.GetJtiByFingerprintFunc(ctx, userID, fingerprint)
}

// GetJtiByFingerprintCalls gets all the calls that were made to GetJtiByFingerprint.
// Check the length with:
//
//	len(mockedPostgres.GetJtiByFingerprintCalls())
func (mock *MockPostgres) GetJtiByFingerprintCalls() []struct {
	Ctx         context.Context
	UserID      uuid.UUID
	Fingerprint core.Fingerprint
} {
	var calls []struct {
		Ctx         context.Context
		UserID      uuid.UUID
		Fingerprint core.Fingerprint
	}
	mock.lockGetJtiByFingerprint.RLock()
	calls = mock.calls.GetJtiByFingerprint
	mock.lockGetJtiByFingerprint.RUnlock()
	return calls
}

// GetRolesByUserID calls GetRolesByUserIDFunc.
func (mock *MockPostgres) GetRolesByUserID(ctx context.Context, userID uuid.UUID) ([]core.Role, error) {
	if mock.GetRolesByUserIDFunc == nil {
		panic("MockPostgres.GetRolesByUserIDFunc: method is nil but Postgres.GetRolesByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetRolesByUserID.Lock()
	mock.calls.GetRolesByUserID = append(mock.calls.GetRolesByUserID, callInfo)
	mock.lockGetRolesByUserID.Unlock()
	return mock.GetRolesByUserIDFunc(ctx, userID)
}

// GetRolesByUserIDCalls gets all the calls that were made to GetRolesByUserID.
// Check the length with:
//
//	len(mockedPostgres.GetRolesByUserIDCalls())
func (mock *MockPostgres) GetRolesByUserIDCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetRolesByUserID.RLock()
	calls = mock.calls.GetRolesByUserID
	mock.lockGetRolesByUserID.RUnlock()
	return calls
}

// GetUserByLogin calls GetUserByLoginFunc.
func (mock *MockPostgres) GetUserByLogin(ctx context.Context, login string) (domain.User, error) {
	if mock.GetUserByLoginFunc == nil {
		panic("MockPostgres.GetUserByLoginFunc: method is nil but Postgres.GetUserByLogin was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Login string
	}{
		Ctx:   ctx,
		Login: login,
	}
	mock.lockGetUserByLogin.Lock()
	mock.calls.GetUserByLogin = append(mock.calls.GetUserByLogin, callInfo)
	mock.lockGetUserByLogin.Unlock()
	return mock.GetUserByLoginFunc(ctx, login)
}

// GetUserByLoginCalls gets all the calls that were made to GetUserByLogin.
// Check the length with:
//
//	len(mockedPostgres.GetUserByLoginCalls())
func (mock *MockPostgres) GetUserByLoginCalls() []struct {
	Ctx   context.Context
	Login string
} {
	var calls []struct {
		Ctx   context.Context
		Login string
	}
	mock.lockGetUserByLogin.RLock()
	calls = mock.calls.GetUserByLogin
	mock.lockGetUserByLogin.RUnlock()
	return calls
}

// Login calls LoginFunc.
func (mock *MockPostgres) Login(ctx context.Context, token domain.RefreshToken) (domain.RefreshToken, error) {
	if mock.LoginFunc == nil {
		panic("MockPostgres.LoginFunc: method is nil but Postgres.Login was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token domain.RefreshToken
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, token)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedPostgres.LoginCalls())
func (mock *MockPostgres) LoginCalls() []struct {
	Ctx   context.Context
	Token domain.RefreshToken
} {
	var calls []struct {
		Ctx   context.Context
		Token domain.RefreshToken
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// Ensure that MockRedis does implement Redis.
// If this is not the case, regenerate this file with mockery.
var _ Redis = &MockRedis{}

// MockRedis is a mock implementation of Redis.
//
//	func TestSomethingThatUsesRedis(t *testing.T) {
//
//		// make and configure a mocked Redis
//		mockedRedis := &MockRedis{
//			DeleteFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Delete method")
//			},
//			SetFunc: func(ctx context.Context, key string, value any, ttl time.Duration) error {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedRedis in code that requires Redis
//		// and then make assertions.
//
//	}
type MockRedis struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, key string) error

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value any, ttl time.Duration) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value any
			// TTL is the ttl argument value.
			TTL time.Duration
		}
	}
	lockDelete sync.RWMutex
	lockSet    sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *MockRedis) Delete(ctx context.Context, key string) error {
	if mock.DeleteFunc == nil {
		panic("MockRedis.DeleteFunc: method is nil but Redis.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedRedis.DeleteCalls())
func (mock *MockRedis) DeleteCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *MockRedis) Set(ctx context.Context, key string, value any, ttl time.Duration) error {
	if mock.SetFunc == nil {
		panic("MockRedis.SetFunc: method is nil but Redis.Set was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value any
		TTL   time.Duration
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
		TTL:   ttl,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, key, value, ttl)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedRedis.SetCalls())
func (mock *MockRedis) SetCalls() []struct {
	Ctx   context.Context
	Key   string
	Value any
	TTL   time.Duration
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value any
		TTL   time.Duration
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// Ensure that MockTokenGenerator does implement TokenGenerator.
// If this is not the case, regenerate this file with mockery.
var _ TokenGenerator = &MockTokenGenerator{}

// MockTokenGenerator is a mock implementation of TokenGenerator.
//
//	func TestSomethingThatUsesTokenGenerator(t *testing.T) {
//
//		// make and configure a mocked TokenGenerator
//		mockedTokenGenerator := &MockTokenGenerator{
//			GenerateAndGetClaimsFunc: func(userID uuid.UUID) (core.AccessToken, core.JwtClaims, error) {
//				panic("mock out the GenerateAndGetClaims method")
//			},
//		}
//
//		// use mockedTokenGenerator in code that requires TokenGenerator
//		// and then make assertions.
//
//	}
type MockTokenGenerator struct {
	// GenerateAndGetClaimsFunc mocks the GenerateAndGetClaims method.
	GenerateAndGetClaimsFunc func(userID uuid.UUID) (core.AccessToken, core.JwtClaims, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateAndGetClaims holds details about calls to the GenerateAndGetClaims method.
		GenerateAndGetClaims []struct {
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
	}
	lockGenerateAndGetClaims sync.RWMutex
}

// GenerateAndGetClaims calls GenerateAndGetClaimsFunc.
func (mock *MockTokenGenerator) GenerateAndGetClaims(userID uuid.UUID) (core.AccessToken, core.JwtClaims, error) {
	if mock.GenerateAndGetClaimsFunc == nil {
		panic("MockTokenGenerator.GenerateAndGetClaimsFunc: method is nil but TokenGenerator.GenerateAndGetClaims was just called")
	}
	callInfo := struct {
		UserID uuid.UUID
	}{
		UserID: userID,
	}
	mock.lockGenerateAndGetClaims.Lock()
	mock.calls.GenerateAndGetClaims = append(mock.calls.GenerateAndGetClaims, callInfo)
	mock.lockGenerateAndGetClaims.Unlock()
	return mock.GenerateAndGetClaimsFunc(userID)
}

// GenerateAndGetClaimsCalls gets all the calls that were made to GenerateAndGetClaims.
// Check the length with:
//
//	len(mockedTokenGenerator.GenerateAndGetClaimsCalls())
func (mock *MockTokenGenerator) GenerateAndGetClaimsCalls() []struct {
	UserID uuid.UUID
} {
	var calls []struct {
		UserID uuid.UUID
	}
	mock.lockGenerateAndGetClaims.RLock()
	calls = mock.calls.GenerateAndGetClaims
	mock.lockGenerateAndGetClaims.RUnlock()
	return calls
}

// Ensure that MockPasswordHasher does implement PasswordHasher.
// If this is not the case, regenerate this file with mockery.
var _ PasswordHasher = &MockPasswordHasher{}

// MockPasswordHasher is a mock implementation of PasswordHasher.
//
//	func TestSomethingThatUsesPasswordHasher(t *testing.T) {
//
//		// make and configure a mocked PasswordHasher
//		mockedPasswordHasher := &MockPasswordHasher{
//			CompareHashAndPasswordFunc: func(hash string, password string) error {
//				panic("mock out the CompareHashAndPassword method")
//			},
//		}
//
//		// use mockedPasswordHasher in code that requires PasswordHasher
//		// and then make assertions.
//
//	}
type MockPasswordHasher struct {
	// CompareHashAndPasswordFunc mocks the CompareHashAndPassword method.
	CompareHashAndPasswordFunc func(hash string, password string) error

	// calls tracks calls to the methods.
	calls struct {
		// CompareHashAndPassword holds details about calls to the CompareHashAndPassword method.
		CompareHashAndPassword []struct {
			// Hash is the hash argument value.
			Hash string
			// Password is the password argument value.
			Password string
		}
	}
	lockCompareHashAndPassword sync.RWMutex
}

// CompareHashAndPassword calls CompareHashAndPasswordFunc.
func (mock *MockPasswordHasher) CompareHashAndPassword(hash string, password string) error {
	if mock.CompareHashAndPasswordFunc == nil {
		panic("MockPasswordHasher.CompareHashAndPasswordFunc: method is nil but PasswordHasher.CompareHashAndPassword was just called")
	}
	callInfo := struct {
		Hash     string
		Password string
	}{
		Hash:     hash,
		Password: password,
	}
	mock.lockCompareHashAndPassword.Lock()
	mock.calls.CompareHashAndPassword = append(mock.calls.CompareHashAndPassword, callInfo)
	mock.lockCompareHashAndPassword.Unlock()
	return mock.CompareHashAndPasswordFunc(hash, password)
}

// CompareHashAndPasswordCalls gets all the calls that were made to CompareHashAndPassword.
// Check the length with:
//
//	len(mockedPasswordHasher.CompareHashAndPasswordCalls())
func (mock *MockPasswordHasher) CompareHashAndPasswordCalls() []struct {
	Hash     string
	Password string
} {
	var calls []struct {
		Hash     string
		Password string
	}
	mock.lockCompareHashAndPassword.RLock()
	calls = mock.calls.CompareHashAndPassword
	mock.lockCompareHashAndPassword.RUnlock()
	return calls
}
