services:
  pinn-gateway:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/services/gateway/cmd/Dockerfile
    container_name: pinn-gateway
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - AUTH_SERVICE_ADDR=http://pinn-auth:8080
      - TASKS_SERVICE_ADDR=http://pinn-tasks:8080
      # HTTP server
      - HTTP_ADDR=${HTTP_ADDR}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - HTTP_IDLE_TIMEOUT=${HTTP_IDLE_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      # Logger
      - LOGGER_ENVIRONMENT=${LOGGER_ENVIRONMENT}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=/app/out/logs
      # Tokens
      - JWT_SECRET=${JWT_SECRET}
      # Redis
      - REDIS_ADDR=redis:${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_DIAL_TIMEOUT=${REDIS_DIAL_TIMEOUT}
      - REDIS_READ_TIMEOUT=${REDIS_READ_TIMEOUT}
      - REDIS_WRITE_TIMEOUT=${REDIS_WRITE_TIMEOUT}
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
      - REDIS_MIN_IDLE_CONNECTIONS=${REDIS_MIN_IDLE_CONNECTIONS}
      - REDIS_POOL_TIMEOUT=${REDIS_POOL_TIMEOUT}
    ports:
      - "8080:8080"
    volumes:
      - ${PROJECT_ROOT}/out/gateway/logs:/app/out/logs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  pinn-auth:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/services/auth/cmd/Dockerfile
    container_name: pinn-auth
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      # HTTP server
      - HTTP_ADDR=${HTTP_ADDR}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - HTTP_IDLE_TIMEOUT=${HTTP_IDLE_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      # Logger
      - LOGGER_ENVIRONMENT=${LOGGER_ENVIRONMENT}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=/app/out/logs
      # Postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=pinn-postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      # Tokens
      - JWT_SECRET=${JWT_SECRET}
      # Redis
      - REDIS_ADDR=redis:${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_DIAL_TIMEOUT=${REDIS_DIAL_TIMEOUT}
      - REDIS_READ_TIMEOUT=${REDIS_READ_TIMEOUT}
      - REDIS_WRITE_TIMEOUT=${REDIS_WRITE_TIMEOUT}
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
      - REDIS_MIN_IDLE_CONNECTIONS=${REDIS_MIN_IDLE_CONNECTIONS}
      - REDIS_POOL_TIMEOUT=${REDIS_POOL_TIMEOUT}
    volumes:
      - ${PROJECT_ROOT}/out/auth/logs:/app/out/logs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  pinn-tasks:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/services/tasks/cmd/Dockerfile
    container_name: pinn-tasks
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      # HTTP server
      - HTTP_ADDR=${HTTP_ADDR}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - HTTP_IDLE_TIMEOUT=${HTTP_IDLE_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      # Logger
      - LOGGER_ENVIRONMENT=${LOGGER_ENVIRONMENT}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=/app/out/logs
      # Postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=pinn-postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      # Kafka
      - KAFKA_WRITER_BROKER=kafka:${KAFKA_PORT}
      - KAFKA_READER_BROKER=kafka:${KAFKA_PORT}
      - KAFKA_READER_GROUP_ID=pinn-automizer
      # Redis
      - REDIS_ADDR=redis:${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_DIAL_TIMEOUT=${REDIS_DIAL_TIMEOUT}
      - REDIS_READ_TIMEOUT=${REDIS_READ_TIMEOUT}
      - REDIS_WRITE_TIMEOUT=${REDIS_WRITE_TIMEOUT}
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
      - REDIS_MIN_IDLE_CONNECTIONS=${REDIS_MIN_IDLE_CONNECTIONS}
      - REDIS_POOL_TIMEOUT=${REDIS_POOL_TIMEOUT}
    volumes:
      - ${PROJECT_ROOT}/out/tasks/logs:/app/out/logs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  pinn-postgres:
    image: postgres:18.1-alpine
    container_name: pinn-env-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    restart: always

  pinn-postgres-goose:
    image: kukymbr/goose-docker:3.27.0
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=pinn-postgres port=${POSTGRES_PORT} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations

  postgres-port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: pinn-postgres-port-forwarder
    command: tcp-listen:${POSTGRES_PORT},fork,reuseaddr tcp-connect:pinn-postgres:${POSTGRES_PORT}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"

  swagger:
    build:
      context: ${PROJECT_ROOT}
      dockerfile_inline: |
        FROM golang:1.26.2-alpine AS builder
        RUN apk add --no-cache git
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        
        FROM golang:1.26.2-alpine
        COPY --from=builder /go/bin/swag /usr/local/bin/swag
        WORKDIR /code
        ENTRYPOINT ["swag"]
    volumes:
      - ${PROJECT_ROOT}:/code

  mockery:
    image: vektra/mockery:3.7
    volumes:
      - ${PROJECT_ROOT}:/src
    working_dir: /src

  redis:
    image: redis:7-alpine
    container_name: pinn-env-redis
    volumes:
      - ${PROJECT_ROOT}/out/redis_data:/redis/data
    command: [ "redis-server", "--appendonly", "yes" ]

  kafka:
    image: apache/kafka:4.1.2
    container_name: pinn-env-kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      # Listeners
      - KAFKA_LISTENERS=PLAINTEXT://:9092,INTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - CLUSTER_ID="qt8ne_I6S6u_Tlh8p6x0og"
      # Logs
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
    volumes:
      - ${PROJECT_ROOT}/out/kafka:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "8888:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9094