services:
  pinn-backend:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/cmd/pinn/Dockerfile
    container_name: pinn-backend
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - HTTP_ADDR=${HTTP_ADDR}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - HTTP_IDLE_TIMEOUT=${HTTP_IDLE_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      - LOGGER_ENVIRONMENT=${LOGGER_ENVIRONMENT}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=/app/out/logs
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=pinn-postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_TOKEN_TTL=${JWT_TOKEN_TTL}
      - REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL}
      - KAFKA_WRITER_ADDR=${KAFKA_WRITER_ADDR}
      - KAFKA_CONSUMER_ADDR=${KAFKA_CONSUMER_ADDR}
      - KAFKA_CONSUMER_ON_TRAIN_TOPIC=${KAFKA_CONSUMER_ON_TRAIN_TOPIC}
      - KAFKA_CONSUMER_AFTER_TRAIN_TOPIC=${KAFKA_CONSUMER_AFTER_TRAIN_TOPIC}
      - KAFKA_CONSUMER_ON_TRAIN_GROUP=${KAFKA_CONSUMER_ON_TRAIN_GROUP}
      - KAFKA_CONSUMER_AFTER_TRAIN_GROUP=${KAFKA_CONSUMER_AFTER_TRAIN_GROUP}
      - REDIS_ADDR=redis:${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_DIAL_TIMEOUT=${REDIS_DIAL_TIMEOUT}
      - REDIS_READ_TIMEOUT=${REDIS_READ_TIMEOUT}
      - REDIS_WRITE_TIMEOUT=${REDIS_WRITE_TIMEOUT}
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
      - REDIS_MIN_IDLE_CONNECTIONS=${REDIS_MIN_IDLE_CONNECTIONS}
      - REDIS_POOL_TIMEOUT=${REDIS_POOL_TIMEOUT}
    volumes:
      - ${PROJECT_ROOT}/out/logs:/app/out/logs
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  pinn-postgres:
    image: postgres:18.1-alpine
    container_name: pinn-env-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    restart: always

  pinn-postgres-goose:
    image: kukymbr/goose-docker:3.27.0
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=pinn-postgres port=5432 user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations

  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: pinn-postgres-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:pinn-postgres:5432
    ports:
      - "127.0.0.1:5432:5432"

  swagger:
    build:
      context: ${PROJECT_ROOT}
      dockerfile_inline: |
        FROM golang:1.26.1-alpine AS builder
        RUN apk add --no-cache git
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        
        FROM golang:1.26.1-alpine
        COPY --from=builder /go/bin/swag /usr/local/bin/swag
        WORKDIR /code
        ENTRYPOINT ["swag"]
    volumes:
      - ${PROJECT_ROOT}:/code

  redis:
    image: redis:7-alpine
    container_name: pinn-env-redis
    volumes:
      - ${PROJECT_ROOT}/out/redis_data:/redis/data
    command: [ "redis-server", "--appendonly", "yes" ]
#  kafka:
#    image: apache/kafka:latest
#    container_name: pinn-automizer-kafka
#    ports:
#      - "9092:9092"
#    environment:
#      # Настройки для работы в режиме KRaft
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    ports:
#      - "8888:8080"
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093 # Internal Docker network address
#    depends_on:
#      - kafka