// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package authRefresh

import (
	"context"
	"sync"

	"github.com/AridanWarlock/pinnAutomizer/internal/domain"
	"github.com/google/uuid"
)

// Ensure that MockUsecase does implement Usecase.
// If this is not the case, regenerate this file with mockery.
var _ Usecase = &MockUsecase{}

// MockUsecase is a mock implementation of Usecase.
//
//	func TestSomethingThatUsesUsecase(t *testing.T) {
//
//		// make and configure a mocked Usecase
//		mockedUsecase := &MockUsecase{
//			RefreshFunc: func(ctx context.Context, in Input) (Output, error) {
//				panic("mock out the Refresh method")
//			},
//		}
//
//		// use mockedUsecase in code that requires Usecase
//		// and then make assertions.
//
//	}
type MockUsecase struct {
	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(ctx context.Context, in Input) (Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In Input
		}
	}
	lockRefresh sync.RWMutex
}

// Refresh calls RefreshFunc.
func (mock *MockUsecase) Refresh(ctx context.Context, in Input) (Output, error) {
	if mock.RefreshFunc == nil {
		panic("MockUsecase.RefreshFunc: method is nil but Usecase.Refresh was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  Input
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(ctx, in)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedUsecase.RefreshCalls())
func (mock *MockUsecase) RefreshCalls() []struct {
	Ctx context.Context
	In  Input
} {
	var calls []struct {
		Ctx context.Context
		In  Input
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// Ensure that MockPostgres does implement Postgres.
// If this is not the case, regenerate this file with mockery.
var _ Postgres = &MockPostgres{}

// MockPostgres is a mock implementation of Postgres.
//
//	func TestSomethingThatUsesPostgres(t *testing.T) {
//
//		// make and configure a mocked Postgres
//		mockedPostgres := &MockPostgres{
//			GetRolesByUserIDFunc: func(ctx context.Context, userID uuid.UUID) ([]domain.Role, error) {
//				panic("mock out the GetRolesByUserID method")
//			},
//			GetUserByIDFunc: func(ctx context.Context, id uuid.UUID) (domain.User, error) {
//				panic("mock out the GetUserByID method")
//			},
//			GetUserSessionByIdFunc: func(ctx context.Context, id uuid.UUID) (domain.UserSession, error) {
//				panic("mock out the GetUserSessionById method")
//			},
//		}
//
//		// use mockedPostgres in code that requires Postgres
//		// and then make assertions.
//
//	}
type MockPostgres struct {
	// GetRolesByUserIDFunc mocks the GetRolesByUserID method.
	GetRolesByUserIDFunc func(ctx context.Context, userID uuid.UUID) ([]domain.Role, error)

	// GetUserByIDFunc mocks the GetUserByID method.
	GetUserByIDFunc func(ctx context.Context, id uuid.UUID) (domain.User, error)

	// GetUserSessionByIdFunc mocks the GetUserSessionById method.
	GetUserSessionByIdFunc func(ctx context.Context, id uuid.UUID) (domain.UserSession, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetRolesByUserID holds details about calls to the GetRolesByUserID method.
		GetRolesByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetUserByID holds details about calls to the GetUserByID method.
		GetUserByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetUserSessionById holds details about calls to the GetUserSessionById method.
		GetUserSessionById []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockGetRolesByUserID   sync.RWMutex
	lockGetUserByID        sync.RWMutex
	lockGetUserSessionById sync.RWMutex
}

// GetRolesByUserID calls GetRolesByUserIDFunc.
func (mock *MockPostgres) GetRolesByUserID(ctx context.Context, userID uuid.UUID) ([]domain.Role, error) {
	if mock.GetRolesByUserIDFunc == nil {
		panic("MockPostgres.GetRolesByUserIDFunc: method is nil but Postgres.GetRolesByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetRolesByUserID.Lock()
	mock.calls.GetRolesByUserID = append(mock.calls.GetRolesByUserID, callInfo)
	mock.lockGetRolesByUserID.Unlock()
	return mock.GetRolesByUserIDFunc(ctx, userID)
}

// GetRolesByUserIDCalls gets all the calls that were made to GetRolesByUserID.
// Check the length with:
//
//	len(mockedPostgres.GetRolesByUserIDCalls())
func (mock *MockPostgres) GetRolesByUserIDCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetRolesByUserID.RLock()
	calls = mock.calls.GetRolesByUserID
	mock.lockGetRolesByUserID.RUnlock()
	return calls
}

// GetUserByID calls GetUserByIDFunc.
func (mock *MockPostgres) GetUserByID(ctx context.Context, id uuid.UUID) (domain.User, error) {
	if mock.GetUserByIDFunc == nil {
		panic("MockPostgres.GetUserByIDFunc: method is nil but Postgres.GetUserByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetUserByID.Lock()
	mock.calls.GetUserByID = append(mock.calls.GetUserByID, callInfo)
	mock.lockGetUserByID.Unlock()
	return mock.GetUserByIDFunc(ctx, id)
}

// GetUserByIDCalls gets all the calls that were made to GetUserByID.
// Check the length with:
//
//	len(mockedPostgres.GetUserByIDCalls())
func (mock *MockPostgres) GetUserByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetUserByID.RLock()
	calls = mock.calls.GetUserByID
	mock.lockGetUserByID.RUnlock()
	return calls
}

// GetUserSessionById calls GetUserSessionByIdFunc.
func (mock *MockPostgres) GetUserSessionById(ctx context.Context, id uuid.UUID) (domain.UserSession, error) {
	if mock.GetUserSessionByIdFunc == nil {
		panic("MockPostgres.GetUserSessionByIdFunc: method is nil but Postgres.GetUserSessionById was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetUserSessionById.Lock()
	mock.calls.GetUserSessionById = append(mock.calls.GetUserSessionById, callInfo)
	mock.lockGetUserSessionById.Unlock()
	return mock.GetUserSessionByIdFunc(ctx, id)
}

// GetUserSessionByIdCalls gets all the calls that were made to GetUserSessionById.
// Check the length with:
//
//	len(mockedPostgres.GetUserSessionByIdCalls())
func (mock *MockPostgres) GetUserSessionByIdCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetUserSessionById.RLock()
	calls = mock.calls.GetUserSessionById
	mock.lockGetUserSessionById.RUnlock()
	return calls
}

// Ensure that MockAccessTokenGenerator does implement AccessTokenGenerator.
// If this is not the case, regenerate this file with mockery.
var _ AccessTokenGenerator = &MockAccessTokenGenerator{}

// MockAccessTokenGenerator is a mock implementation of AccessTokenGenerator.
//
//	func TestSomethingThatUsesAccessTokenGenerator(t *testing.T) {
//
//		// make and configure a mocked AccessTokenGenerator
//		mockedAccessTokenGenerator := &MockAccessTokenGenerator{
//			GenerateFunc: func(user domain.User, roles []domain.Role, fingerprint domain.Fingerprint) (domain.AccessToken, error) {
//				panic("mock out the Generate method")
//			},
//		}
//
//		// use mockedAccessTokenGenerator in code that requires AccessTokenGenerator
//		// and then make assertions.
//
//	}
type MockAccessTokenGenerator struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func(user domain.User, roles []domain.Role, fingerprint domain.Fingerprint) (domain.AccessToken, error)

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// User is the user argument value.
			User domain.User
			// Roles is the roles argument value.
			Roles []domain.Role
			// Fingerprint is the fingerprint argument value.
			Fingerprint domain.Fingerprint
		}
	}
	lockGenerate sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *MockAccessTokenGenerator) Generate(user domain.User, roles []domain.Role, fingerprint domain.Fingerprint) (domain.AccessToken, error) {
	if mock.GenerateFunc == nil {
		panic("MockAccessTokenGenerator.GenerateFunc: method is nil but AccessTokenGenerator.Generate was just called")
	}
	callInfo := struct {
		User        domain.User
		Roles       []domain.Role
		Fingerprint domain.Fingerprint
	}{
		User:        user,
		Roles:       roles,
		Fingerprint: fingerprint,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	return mock.GenerateFunc(user, roles, fingerprint)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedAccessTokenGenerator.GenerateCalls())
func (mock *MockAccessTokenGenerator) GenerateCalls() []struct {
	User        domain.User
	Roles       []domain.Role
	Fingerprint domain.Fingerprint
} {
	var calls []struct {
		User        domain.User
		Roles       []domain.Role
		Fingerprint domain.Fingerprint
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}
