// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package authRefresh

import (
	"context"
	"sync"
	"time"

	"github.com/AridanWarlock/pinnAutomizer/internal/domain"
	"github.com/google/uuid"
)

// Ensure that MockUsecase does implement Usecase.
// If this is not the case, regenerate this file with mockery.
var _ Usecase = &MockUsecase{}

// MockUsecase is a mock implementation of Usecase.
//
//	func TestSomethingThatUsesUsecase(t *testing.T) {
//
//		// make and configure a mocked Usecase
//		mockedUsecase := &MockUsecase{
//			RefreshFunc: func(ctx context.Context, in Input) (Output, error) {
//				panic("mock out the Refresh method")
//			},
//		}
//
//		// use mockedUsecase in code that requires Usecase
//		// and then make assertions.
//
//	}
type MockUsecase struct {
	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(ctx context.Context, in Input) (Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In Input
		}
	}
	lockRefresh sync.RWMutex
}

// Refresh calls RefreshFunc.
func (mock *MockUsecase) Refresh(ctx context.Context, in Input) (Output, error) {
	if mock.RefreshFunc == nil {
		panic("MockUsecase.RefreshFunc: method is nil but Usecase.Refresh was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  Input
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(ctx, in)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedUsecase.RefreshCalls())
func (mock *MockUsecase) RefreshCalls() []struct {
	Ctx context.Context
	In  Input
} {
	var calls []struct {
		Ctx context.Context
		In  Input
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// Ensure that MockPostgres does implement Postgres.
// If this is not the case, regenerate this file with mockery.
var _ Postgres = &MockPostgres{}

// MockPostgres is a mock implementation of Postgres.
//
//	func TestSomethingThatUsesPostgres(t *testing.T) {
//
//		// make and configure a mocked Postgres
//		mockedPostgres := &MockPostgres{
//			GetRefreshTokenByHashFunc: func(ctx context.Context, hash string) (domain.RefreshToken, error) {
//				panic("mock out the GetRefreshTokenByHash method")
//			},
//			GetRolesByUserIDFunc: func(ctx context.Context, userID uuid.UUID) ([]domain.Role, error) {
//				panic("mock out the GetRolesByUserID method")
//			},
//			RotateRefreshTokenFunc: func(ctx context.Context, oldHash string, newHash string, newJti domain.Jti) error {
//				panic("mock out the RotateRefreshToken method")
//			},
//		}
//
//		// use mockedPostgres in code that requires Postgres
//		// and then make assertions.
//
//	}
type MockPostgres struct {
	// GetRefreshTokenByHashFunc mocks the GetRefreshTokenByHash method.
	GetRefreshTokenByHashFunc func(ctx context.Context, hash string) (domain.RefreshToken, error)

	// GetRolesByUserIDFunc mocks the GetRolesByUserID method.
	GetRolesByUserIDFunc func(ctx context.Context, userID uuid.UUID) ([]domain.Role, error)

	// RotateRefreshTokenFunc mocks the RotateRefreshToken method.
	RotateRefreshTokenFunc func(ctx context.Context, oldHash string, newHash string, newJti domain.Jti) error

	// calls tracks calls to the methods.
	calls struct {
		// GetRefreshTokenByHash holds details about calls to the GetRefreshTokenByHash method.
		GetRefreshTokenByHash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
		}
		// GetRolesByUserID holds details about calls to the GetRolesByUserID method.
		GetRolesByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// RotateRefreshToken holds details about calls to the RotateRefreshToken method.
		RotateRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OldHash is the oldHash argument value.
			OldHash string
			// NewHash is the newHash argument value.
			NewHash string
			// NewJti is the newJti argument value.
			NewJti domain.Jti
		}
	}
	lockGetRefreshTokenByHash sync.RWMutex
	lockGetRolesByUserID      sync.RWMutex
	lockRotateRefreshToken    sync.RWMutex
}

// GetRefreshTokenByHash calls GetRefreshTokenByHashFunc.
func (mock *MockPostgres) GetRefreshTokenByHash(ctx context.Context, hash string) (domain.RefreshToken, error) {
	if mock.GetRefreshTokenByHashFunc == nil {
		panic("MockPostgres.GetRefreshTokenByHashFunc: method is nil but Postgres.GetRefreshTokenByHash was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Hash string
	}{
		Ctx:  ctx,
		Hash: hash,
	}
	mock.lockGetRefreshTokenByHash.Lock()
	mock.calls.GetRefreshTokenByHash = append(mock.calls.GetRefreshTokenByHash, callInfo)
	mock.lockGetRefreshTokenByHash.Unlock()
	return mock.GetRefreshTokenByHashFunc(ctx, hash)
}

// GetRefreshTokenByHashCalls gets all the calls that were made to GetRefreshTokenByHash.
// Check the length with:
//
//	len(mockedPostgres.GetRefreshTokenByHashCalls())
func (mock *MockPostgres) GetRefreshTokenByHashCalls() []struct {
	Ctx  context.Context
	Hash string
} {
	var calls []struct {
		Ctx  context.Context
		Hash string
	}
	mock.lockGetRefreshTokenByHash.RLock()
	calls = mock.calls.GetRefreshTokenByHash
	mock.lockGetRefreshTokenByHash.RUnlock()
	return calls
}

// GetRolesByUserID calls GetRolesByUserIDFunc.
func (mock *MockPostgres) GetRolesByUserID(ctx context.Context, userID uuid.UUID) ([]domain.Role, error) {
	if mock.GetRolesByUserIDFunc == nil {
		panic("MockPostgres.GetRolesByUserIDFunc: method is nil but Postgres.GetRolesByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetRolesByUserID.Lock()
	mock.calls.GetRolesByUserID = append(mock.calls.GetRolesByUserID, callInfo)
	mock.lockGetRolesByUserID.Unlock()
	return mock.GetRolesByUserIDFunc(ctx, userID)
}

// GetRolesByUserIDCalls gets all the calls that were made to GetRolesByUserID.
// Check the length with:
//
//	len(mockedPostgres.GetRolesByUserIDCalls())
func (mock *MockPostgres) GetRolesByUserIDCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetRolesByUserID.RLock()
	calls = mock.calls.GetRolesByUserID
	mock.lockGetRolesByUserID.RUnlock()
	return calls
}

// RotateRefreshToken calls RotateRefreshTokenFunc.
func (mock *MockPostgres) RotateRefreshToken(ctx context.Context, oldHash string, newHash string, newJti domain.Jti) error {
	if mock.RotateRefreshTokenFunc == nil {
		panic("MockPostgres.RotateRefreshTokenFunc: method is nil but Postgres.RotateRefreshToken was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OldHash string
		NewHash string
		NewJti  domain.Jti
	}{
		Ctx:     ctx,
		OldHash: oldHash,
		NewHash: newHash,
		NewJti:  newJti,
	}
	mock.lockRotateRefreshToken.Lock()
	mock.calls.RotateRefreshToken = append(mock.calls.RotateRefreshToken, callInfo)
	mock.lockRotateRefreshToken.Unlock()
	return mock.RotateRefreshTokenFunc(ctx, oldHash, newHash, newJti)
}

// RotateRefreshTokenCalls gets all the calls that were made to RotateRefreshToken.
// Check the length with:
//
//	len(mockedPostgres.RotateRefreshTokenCalls())
func (mock *MockPostgres) RotateRefreshTokenCalls() []struct {
	Ctx     context.Context
	OldHash string
	NewHash string
	NewJti  domain.Jti
} {
	var calls []struct {
		Ctx     context.Context
		OldHash string
		NewHash string
		NewJti  domain.Jti
	}
	mock.lockRotateRefreshToken.RLock()
	calls = mock.calls.RotateRefreshToken
	mock.lockRotateRefreshToken.RUnlock()
	return calls
}

// Ensure that MockRedis does implement Redis.
// If this is not the case, regenerate this file with mockery.
var _ Redis = &MockRedis{}

// MockRedis is a mock implementation of Redis.
//
//	func TestSomethingThatUsesRedis(t *testing.T) {
//
//		// make and configure a mocked Redis
//		mockedRedis := &MockRedis{
//			DeleteFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Delete method")
//			},
//			SetFunc: func(ctx context.Context, key string, value any, ttl time.Duration) error {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedRedis in code that requires Redis
//		// and then make assertions.
//
//	}
type MockRedis struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, key string) error

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value any, ttl time.Duration) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value any
			// TTL is the ttl argument value.
			TTL time.Duration
		}
	}
	lockDelete sync.RWMutex
	lockSet    sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *MockRedis) Delete(ctx context.Context, key string) error {
	if mock.DeleteFunc == nil {
		panic("MockRedis.DeleteFunc: method is nil but Redis.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedRedis.DeleteCalls())
func (mock *MockRedis) DeleteCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *MockRedis) Set(ctx context.Context, key string, value any, ttl time.Duration) error {
	if mock.SetFunc == nil {
		panic("MockRedis.SetFunc: method is nil but Redis.Set was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value any
		TTL   time.Duration
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
		TTL:   ttl,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, key, value, ttl)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedRedis.SetCalls())
func (mock *MockRedis) SetCalls() []struct {
	Ctx   context.Context
	Key   string
	Value any
	TTL   time.Duration
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value any
		TTL   time.Duration
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// Ensure that MockTokenGenerator does implement TokenGenerator.
// If this is not the case, regenerate this file with mockery.
var _ TokenGenerator = &MockTokenGenerator{}

// MockTokenGenerator is a mock implementation of TokenGenerator.
//
//	func TestSomethingThatUsesTokenGenerator(t *testing.T) {
//
//		// make and configure a mocked TokenGenerator
//		mockedTokenGenerator := &MockTokenGenerator{
//			GenerateAndGetClaimsFunc: func(userID uuid.UUID) (domain.AccessToken, domain.JwtClaims, error) {
//				panic("mock out the GenerateAndGetClaims method")
//			},
//		}
//
//		// use mockedTokenGenerator in code that requires TokenGenerator
//		// and then make assertions.
//
//	}
type MockTokenGenerator struct {
	// GenerateAndGetClaimsFunc mocks the GenerateAndGetClaims method.
	GenerateAndGetClaimsFunc func(userID uuid.UUID) (domain.AccessToken, domain.JwtClaims, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateAndGetClaims holds details about calls to the GenerateAndGetClaims method.
		GenerateAndGetClaims []struct {
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
	}
	lockGenerateAndGetClaims sync.RWMutex
}

// GenerateAndGetClaims calls GenerateAndGetClaimsFunc.
func (mock *MockTokenGenerator) GenerateAndGetClaims(userID uuid.UUID) (domain.AccessToken, domain.JwtClaims, error) {
	if mock.GenerateAndGetClaimsFunc == nil {
		panic("MockTokenGenerator.GenerateAndGetClaimsFunc: method is nil but TokenGenerator.GenerateAndGetClaims was just called")
	}
	callInfo := struct {
		UserID uuid.UUID
	}{
		UserID: userID,
	}
	mock.lockGenerateAndGetClaims.Lock()
	mock.calls.GenerateAndGetClaims = append(mock.calls.GenerateAndGetClaims, callInfo)
	mock.lockGenerateAndGetClaims.Unlock()
	return mock.GenerateAndGetClaimsFunc(userID)
}

// GenerateAndGetClaimsCalls gets all the calls that were made to GenerateAndGetClaims.
// Check the length with:
//
//	len(mockedTokenGenerator.GenerateAndGetClaimsCalls())
func (mock *MockTokenGenerator) GenerateAndGetClaimsCalls() []struct {
	UserID uuid.UUID
} {
	var calls []struct {
		UserID uuid.UUID
	}
	mock.lockGenerateAndGetClaims.RLock()
	calls = mock.calls.GenerateAndGetClaims
	mock.lockGenerateAndGetClaims.RUnlock()
	return calls
}
