// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package authLogin

import (
	"context"
	"sync"

	"github.com/AridanWarlock/pinnAutomizer/internal/domain"
	"github.com/google/uuid"
)

// Ensure that MockUsecase does implement Usecase.
// If this is not the case, regenerate this file with mockery.
var _ Usecase = &MockUsecase{}

// MockUsecase is a mock implementation of Usecase.
//
//	func TestSomethingThatUsesUsecase(t *testing.T) {
//
//		// make and configure a mocked Usecase
//		mockedUsecase := &MockUsecase{
//			LoginFunc: func(ctx context.Context, in Input) (Output, error) {
//				panic("mock out the Login method")
//			},
//		}
//
//		// use mockedUsecase in code that requires Usecase
//		// and then make assertions.
//
//	}
type MockUsecase struct {
	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, in Input) (Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In Input
		}
	}
	lockLogin sync.RWMutex
}

// Login calls LoginFunc.
func (mock *MockUsecase) Login(ctx context.Context, in Input) (Output, error) {
	if mock.LoginFunc == nil {
		panic("MockUsecase.LoginFunc: method is nil but Usecase.Login was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  Input
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, in)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedUsecase.LoginCalls())
func (mock *MockUsecase) LoginCalls() []struct {
	Ctx context.Context
	In  Input
} {
	var calls []struct {
		Ctx context.Context
		In  Input
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// Ensure that MockPostgres does implement Postgres.
// If this is not the case, regenerate this file with mockery.
var _ Postgres = &MockPostgres{}

// MockPostgres is a mock implementation of Postgres.
//
//	func TestSomethingThatUsesPostgres(t *testing.T) {
//
//		// make and configure a mocked Postgres
//		mockedPostgres := &MockPostgres{
//			GetRolesByUserIDFunc: func(ctx context.Context, userID uuid.UUID) ([]domain.Role, error) {
//				panic("mock out the GetRolesByUserID method")
//			},
//			GetUserByLoginFunc: func(ctx context.Context, login string) (domain.User, error) {
//				panic("mock out the GetUserByLogin method")
//			},
//			LoginFunc: func(ctx context.Context, session domain.UserSession) error {
//				panic("mock out the Login method")
//			},
//		}
//
//		// use mockedPostgres in code that requires Postgres
//		// and then make assertions.
//
//	}
type MockPostgres struct {
	// GetRolesByUserIDFunc mocks the GetRolesByUserID method.
	GetRolesByUserIDFunc func(ctx context.Context, userID uuid.UUID) ([]domain.Role, error)

	// GetUserByLoginFunc mocks the GetUserByLogin method.
	GetUserByLoginFunc func(ctx context.Context, login string) (domain.User, error)

	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, session domain.UserSession) error

	// calls tracks calls to the methods.
	calls struct {
		// GetRolesByUserID holds details about calls to the GetRolesByUserID method.
		GetRolesByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetUserByLogin holds details about calls to the GetUserByLogin method.
		GetUserByLogin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Login is the login argument value.
			Login string
		}
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Session is the session argument value.
			Session domain.UserSession
		}
	}
	lockGetRolesByUserID sync.RWMutex
	lockGetUserByLogin   sync.RWMutex
	lockLogin            sync.RWMutex
}

// GetRolesByUserID calls GetRolesByUserIDFunc.
func (mock *MockPostgres) GetRolesByUserID(ctx context.Context, userID uuid.UUID) ([]domain.Role, error) {
	if mock.GetRolesByUserIDFunc == nil {
		panic("MockPostgres.GetRolesByUserIDFunc: method is nil but Postgres.GetRolesByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetRolesByUserID.Lock()
	mock.calls.GetRolesByUserID = append(mock.calls.GetRolesByUserID, callInfo)
	mock.lockGetRolesByUserID.Unlock()
	return mock.GetRolesByUserIDFunc(ctx, userID)
}

// GetRolesByUserIDCalls gets all the calls that were made to GetRolesByUserID.
// Check the length with:
//
//	len(mockedPostgres.GetRolesByUserIDCalls())
func (mock *MockPostgres) GetRolesByUserIDCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetRolesByUserID.RLock()
	calls = mock.calls.GetRolesByUserID
	mock.lockGetRolesByUserID.RUnlock()
	return calls
}

// GetUserByLogin calls GetUserByLoginFunc.
func (mock *MockPostgres) GetUserByLogin(ctx context.Context, login string) (domain.User, error) {
	if mock.GetUserByLoginFunc == nil {
		panic("MockPostgres.GetUserByLoginFunc: method is nil but Postgres.GetUserByLogin was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Login string
	}{
		Ctx:   ctx,
		Login: login,
	}
	mock.lockGetUserByLogin.Lock()
	mock.calls.GetUserByLogin = append(mock.calls.GetUserByLogin, callInfo)
	mock.lockGetUserByLogin.Unlock()
	return mock.GetUserByLoginFunc(ctx, login)
}

// GetUserByLoginCalls gets all the calls that were made to GetUserByLogin.
// Check the length with:
//
//	len(mockedPostgres.GetUserByLoginCalls())
func (mock *MockPostgres) GetUserByLoginCalls() []struct {
	Ctx   context.Context
	Login string
} {
	var calls []struct {
		Ctx   context.Context
		Login string
	}
	mock.lockGetUserByLogin.RLock()
	calls = mock.calls.GetUserByLogin
	mock.lockGetUserByLogin.RUnlock()
	return calls
}

// Login calls LoginFunc.
func (mock *MockPostgres) Login(ctx context.Context, session domain.UserSession) error {
	if mock.LoginFunc == nil {
		panic("MockPostgres.LoginFunc: method is nil but Postgres.Login was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Session domain.UserSession
	}{
		Ctx:     ctx,
		Session: session,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, session)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedPostgres.LoginCalls())
func (mock *MockPostgres) LoginCalls() []struct {
	Ctx     context.Context
	Session domain.UserSession
} {
	var calls []struct {
		Ctx     context.Context
		Session domain.UserSession
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// Ensure that MockAccessTokenGenerator does implement AccessTokenGenerator.
// If this is not the case, regenerate this file with mockery.
var _ AccessTokenGenerator = &MockAccessTokenGenerator{}

// MockAccessTokenGenerator is a mock implementation of AccessTokenGenerator.
//
//	func TestSomethingThatUsesAccessTokenGenerator(t *testing.T) {
//
//		// make and configure a mocked AccessTokenGenerator
//		mockedAccessTokenGenerator := &MockAccessTokenGenerator{
//			GenerateFunc: func(user domain.User, roles []domain.Role) (domain.AccessToken, error) {
//				panic("mock out the Generate method")
//			},
//		}
//
//		// use mockedAccessTokenGenerator in code that requires AccessTokenGenerator
//		// and then make assertions.
//
//	}
type MockAccessTokenGenerator struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func(user domain.User, roles []domain.Role) (domain.AccessToken, error)

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// User is the user argument value.
			User domain.User
			// Roles is the roles argument value.
			Roles []domain.Role
		}
	}
	lockGenerate sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *MockAccessTokenGenerator) Generate(user domain.User, roles []domain.Role) (domain.AccessToken, error) {
	if mock.GenerateFunc == nil {
		panic("MockAccessTokenGenerator.GenerateFunc: method is nil but AccessTokenGenerator.Generate was just called")
	}
	callInfo := struct {
		User  domain.User
		Roles []domain.Role
	}{
		User:  user,
		Roles: roles,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	return mock.GenerateFunc(user, roles)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedAccessTokenGenerator.GenerateCalls())
func (mock *MockAccessTokenGenerator) GenerateCalls() []struct {
	User  domain.User
	Roles []domain.Role
} {
	var calls []struct {
		User  domain.User
		Roles []domain.Role
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}

// Ensure that MockRefreshTokenGenerator does implement RefreshTokenGenerator.
// If this is not the case, regenerate this file with mockery.
var _ RefreshTokenGenerator = &MockRefreshTokenGenerator{}

// MockRefreshTokenGenerator is a mock implementation of RefreshTokenGenerator.
//
//	func TestSomethingThatUsesRefreshTokenGenerator(t *testing.T) {
//
//		// make and configure a mocked RefreshTokenGenerator
//		mockedRefreshTokenGenerator := &MockRefreshTokenGenerator{
//			GenerateFunc: func() (domain.RefreshToken, error) {
//				panic("mock out the Generate method")
//			},
//		}
//
//		// use mockedRefreshTokenGenerator in code that requires RefreshTokenGenerator
//		// and then make assertions.
//
//	}
type MockRefreshTokenGenerator struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func() (domain.RefreshToken, error)

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
		}
	}
	lockGenerate sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *MockRefreshTokenGenerator) Generate() (domain.RefreshToken, error) {
	if mock.GenerateFunc == nil {
		panic("MockRefreshTokenGenerator.GenerateFunc: method is nil but RefreshTokenGenerator.Generate was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	return mock.GenerateFunc()
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedRefreshTokenGenerator.GenerateCalls())
func (mock *MockRefreshTokenGenerator) GenerateCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}

// Ensure that MockPasswordHasher does implement PasswordHasher.
// If this is not the case, regenerate this file with mockery.
var _ PasswordHasher = &MockPasswordHasher{}

// MockPasswordHasher is a mock implementation of PasswordHasher.
//
//	func TestSomethingThatUsesPasswordHasher(t *testing.T) {
//
//		// make and configure a mocked PasswordHasher
//		mockedPasswordHasher := &MockPasswordHasher{
//			CompareHashAndPasswordFunc: func(hasherPassword string, password string) error {
//				panic("mock out the CompareHashAndPassword method")
//			},
//		}
//
//		// use mockedPasswordHasher in code that requires PasswordHasher
//		// and then make assertions.
//
//	}
type MockPasswordHasher struct {
	// CompareHashAndPasswordFunc mocks the CompareHashAndPassword method.
	CompareHashAndPasswordFunc func(hasherPassword string, password string) error

	// calls tracks calls to the methods.
	calls struct {
		// CompareHashAndPassword holds details about calls to the CompareHashAndPassword method.
		CompareHashAndPassword []struct {
			// HasherPassword is the hasherPassword argument value.
			HasherPassword string
			// Password is the password argument value.
			Password string
		}
	}
	lockCompareHashAndPassword sync.RWMutex
}

// CompareHashAndPassword calls CompareHashAndPasswordFunc.
func (mock *MockPasswordHasher) CompareHashAndPassword(hasherPassword string, password string) error {
	if mock.CompareHashAndPasswordFunc == nil {
		panic("MockPasswordHasher.CompareHashAndPasswordFunc: method is nil but PasswordHasher.CompareHashAndPassword was just called")
	}
	callInfo := struct {
		HasherPassword string
		Password       string
	}{
		HasherPassword: hasherPassword,
		Password:       password,
	}
	mock.lockCompareHashAndPassword.Lock()
	mock.calls.CompareHashAndPassword = append(mock.calls.CompareHashAndPassword, callInfo)
	mock.lockCompareHashAndPassword.Unlock()
	return mock.CompareHashAndPasswordFunc(hasherPassword, password)
}

// CompareHashAndPasswordCalls gets all the calls that were made to CompareHashAndPassword.
// Check the length with:
//
//	len(mockedPasswordHasher.CompareHashAndPasswordCalls())
func (mock *MockPasswordHasher) CompareHashAndPasswordCalls() []struct {
	HasherPassword string
	Password       string
} {
	var calls []struct {
		HasherPassword string
		Password       string
	}
	mock.lockCompareHashAndPassword.RLock()
	calls = mock.calls.CompareHashAndPassword
	mock.lockCompareHashAndPassword.RUnlock()
	return calls
}
