// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authLogin

import (
	"context"
	"github.com/AridanWarlock/pinnAutomizer/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgres creates a new instance of MockPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgres {
	mock := &MockPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgres is an autogenerated mock type for the Postgres type
type MockPostgres struct {
	mock.Mock
}

type MockPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgres) EXPECT() *MockPostgres_Expecter {
	return &MockPostgres_Expecter{mock: &_m.Mock}
}

// GetUserByLogin provides a mock function for the type MockPostgres
func (_mock *MockPostgres) GetUserByLogin(ctx context.Context, login string) (domain.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockPostgres_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockPostgres_Expecter) GetUserByLogin(ctx interface{}, login interface{}) *MockPostgres_GetUserByLogin_Call {
	return &MockPostgres_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", ctx, login)}
}

func (_c *MockPostgres_GetUserByLogin_Call) Run(run func(ctx context.Context, login string)) *MockPostgres_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_GetUserByLogin_Call) Return(user domain.User, err error) *MockPostgres_GetUserByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockPostgres_GetUserByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (domain.User, error)) *MockPostgres_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockPostgres
func (_mock *MockPostgres) Login(ctx context.Context, tokens domain.AuthToken) error {
	ret := _mock.Called(ctx, tokens)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AuthToken) error); ok {
		r0 = returnFunc(ctx, tokens)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockPostgres_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - tokens domain.AuthToken
func (_e *MockPostgres_Expecter) Login(ctx interface{}, tokens interface{}) *MockPostgres_Login_Call {
	return &MockPostgres_Login_Call{Call: _e.mock.On("Login", ctx, tokens)}
}

func (_c *MockPostgres_Login_Call) Run(run func(ctx context.Context, tokens domain.AuthToken)) *MockPostgres_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AuthToken
		if args[1] != nil {
			arg1 = args[1].(domain.AuthToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_Login_Call) Return(err error) *MockPostgres_Login_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_Login_Call) RunAndReturn(run func(ctx context.Context, tokens domain.AuthToken) error) *MockPostgres_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwtService creates a new instance of MockJwtService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwtService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwtService {
	mock := &MockJwtService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwtService is an autogenerated mock type for the JwtService type
type MockJwtService struct {
	mock.Mock
}

type MockJwtService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwtService) EXPECT() *MockJwtService_Expecter {
	return &MockJwtService_Expecter{mock: &_m.Mock}
}

// GenerateTokensPair provides a mock function for the type MockJwtService
func (_mock *MockJwtService) GenerateTokensPair(userID uuid.UUID) (domain.TokensPair, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokensPair")
	}

	var r0 domain.TokensPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (domain.TokensPair, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) domain.TokensPair); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(domain.TokensPair)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwtService_GenerateTokensPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokensPair'
type MockJwtService_GenerateTokensPair_Call struct {
	*mock.Call
}

// GenerateTokensPair is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockJwtService_Expecter) GenerateTokensPair(userID interface{}) *MockJwtService_GenerateTokensPair_Call {
	return &MockJwtService_GenerateTokensPair_Call{Call: _e.mock.On("GenerateTokensPair", userID)}
}

func (_c *MockJwtService_GenerateTokensPair_Call) Run(run func(userID uuid.UUID)) *MockJwtService_GenerateTokensPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJwtService_GenerateTokensPair_Call) Return(tokensPair domain.TokensPair, err error) *MockJwtService_GenerateTokensPair_Call {
	_c.Call.Return(tokensPair, err)
	return _c
}

func (_c *MockJwtService_GenerateTokensPair_Call) RunAndReturn(run func(userID uuid.UUID) (domain.TokensPair, error)) *MockJwtService_GenerateTokensPair_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordHasher creates a new instance of MockPasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordHasher {
	mock := &MockPasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordHasher is an autogenerated mock type for the PasswordHasher type
type MockPasswordHasher struct {
	mock.Mock
}

type MockPasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordHasher) EXPECT() *MockPasswordHasher_Expecter {
	return &MockPasswordHasher_Expecter{mock: &_m.Mock}
}

// CompareHashAndPassword provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) CompareHashAndPassword(hasherPassword string, password string) error {
	ret := _mock.Called(hasherPassword, password)

	if len(ret) == 0 {
		panic("no return value specified for CompareHashAndPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hasherPassword, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordHasher_CompareHashAndPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareHashAndPassword'
type MockPasswordHasher_CompareHashAndPassword_Call struct {
	*mock.Call
}

// CompareHashAndPassword is a helper method to define mock.On call
//   - hasherPassword string
//   - password string
func (_e *MockPasswordHasher_Expecter) CompareHashAndPassword(hasherPassword interface{}, password interface{}) *MockPasswordHasher_CompareHashAndPassword_Call {
	return &MockPasswordHasher_CompareHashAndPassword_Call{Call: _e.mock.On("CompareHashAndPassword", hasherPassword, password)}
}

func (_c *MockPasswordHasher_CompareHashAndPassword_Call) Run(run func(hasherPassword string, password string)) *MockPasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordHasher_CompareHashAndPassword_Call) Return(err error) *MockPasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordHasher_CompareHashAndPassword_Call) RunAndReturn(run func(hasherPassword string, password string) error) *MockPasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Return(run)
	return _c
}
