// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package tasksCreate

import (
	"context"
	"sync"

	"github.com/AridanWarlock/pinnAutomizer/pkg/core"
	"github.com/AridanWarlock/pinnAutomizer/tasks/internal/domain"
)

// Ensure that MockUsecase does implement Usecase.
// If this is not the case, regenerate this file with mockery.
var _ Usecase = &MockUsecase{}

// MockUsecase is a mock implementation of Usecase.
//
//	func TestSomethingThatUsesUsecase(t *testing.T) {
//
//		// make and configure a mocked Usecase
//		mockedUsecase := &MockUsecase{
//			CreateTaskFunc: func(ctx context.Context, in Input) (Output, error) {
//				panic("mock out the CreateTask method")
//			},
//		}
//
//		// use mockedUsecase in code that requires Usecase
//		// and then make assertions.
//
//	}
type MockUsecase struct {
	// CreateTaskFunc mocks the CreateTask method.
	CreateTaskFunc func(ctx context.Context, in Input) (Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateTask holds details about calls to the CreateTask method.
		CreateTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In Input
		}
	}
	lockCreateTask sync.RWMutex
}

// CreateTask calls CreateTaskFunc.
func (mock *MockUsecase) CreateTask(ctx context.Context, in Input) (Output, error) {
	if mock.CreateTaskFunc == nil {
		panic("MockUsecase.CreateTaskFunc: method is nil but Usecase.CreateTask was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  Input
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockCreateTask.Lock()
	mock.calls.CreateTask = append(mock.calls.CreateTask, callInfo)
	mock.lockCreateTask.Unlock()
	return mock.CreateTaskFunc(ctx, in)
}

// CreateTaskCalls gets all the calls that were made to CreateTask.
// Check the length with:
//
//	len(mockedUsecase.CreateTaskCalls())
func (mock *MockUsecase) CreateTaskCalls() []struct {
	Ctx context.Context
	In  Input
} {
	var calls []struct {
		Ctx context.Context
		In  Input
	}
	mock.lockCreateTask.RLock()
	calls = mock.calls.CreateTask
	mock.lockCreateTask.RUnlock()
	return calls
}

// Ensure that MockPostgres does implement Postgres.
// If this is not the case, regenerate this file with mockery.
var _ Postgres = &MockPostgres{}

// MockPostgres is a mock implementation of Postgres.
//
//	func TestSomethingThatUsesPostgres(t *testing.T) {
//
//		// make and configure a mocked Postgres
//		mockedPostgres := &MockPostgres{
//			CreateTaskFunc: func(ctx context.Context, task domain.Task) (domain.Task, error) {
//				panic("mock out the CreateTask method")
//			},
//			GetEquationByTypeFunc: func(ctx context.Context, equationType string) (domain.Equation, error) {
//				panic("mock out the GetEquationByType method")
//			},
//			InTransactionFunc: func(ctx context.Context, inTx func(ctx context.Context) error) error {
//				panic("mock out the InTransaction method")
//			},
//			PublishEventFunc: func(ctx context.Context, event domain.Event) (domain.Event, error) {
//				panic("mock out the PublishEvent method")
//			},
//		}
//
//		// use mockedPostgres in code that requires Postgres
//		// and then make assertions.
//
//	}
type MockPostgres struct {
	// CreateTaskFunc mocks the CreateTask method.
	CreateTaskFunc func(ctx context.Context, task domain.Task) (domain.Task, error)

	// GetEquationByTypeFunc mocks the GetEquationByType method.
	GetEquationByTypeFunc func(ctx context.Context, equationType string) (domain.Equation, error)

	// InTransactionFunc mocks the InTransaction method.
	InTransactionFunc func(ctx context.Context, inTx func(ctx context.Context) error) error

	// PublishEventFunc mocks the PublishEvent method.
	PublishEventFunc func(ctx context.Context, event domain.Event) (domain.Event, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateTask holds details about calls to the CreateTask method.
		CreateTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Task is the task argument value.
			Task domain.Task
		}
		// GetEquationByType holds details about calls to the GetEquationByType method.
		GetEquationByType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EquationType is the equationType argument value.
			EquationType string
		}
		// InTransaction holds details about calls to the InTransaction method.
		InTransaction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InTx is the inTx argument value.
			InTx func(ctx context.Context) error
		}
		// PublishEvent holds details about calls to the PublishEvent method.
		PublishEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event domain.Event
		}
	}
	lockCreateTask        sync.RWMutex
	lockGetEquationByType sync.RWMutex
	lockInTransaction     sync.RWMutex
	lockPublishEvent      sync.RWMutex
}

// CreateTask calls CreateTaskFunc.
func (mock *MockPostgres) CreateTask(ctx context.Context, task domain.Task) (domain.Task, error) {
	if mock.CreateTaskFunc == nil {
		panic("MockPostgres.CreateTaskFunc: method is nil but Postgres.CreateTask was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Task domain.Task
	}{
		Ctx:  ctx,
		Task: task,
	}
	mock.lockCreateTask.Lock()
	mock.calls.CreateTask = append(mock.calls.CreateTask, callInfo)
	mock.lockCreateTask.Unlock()
	return mock.CreateTaskFunc(ctx, task)
}

// CreateTaskCalls gets all the calls that were made to CreateTask.
// Check the length with:
//
//	len(mockedPostgres.CreateTaskCalls())
func (mock *MockPostgres) CreateTaskCalls() []struct {
	Ctx  context.Context
	Task domain.Task
} {
	var calls []struct {
		Ctx  context.Context
		Task domain.Task
	}
	mock.lockCreateTask.RLock()
	calls = mock.calls.CreateTask
	mock.lockCreateTask.RUnlock()
	return calls
}

// GetEquationByType calls GetEquationByTypeFunc.
func (mock *MockPostgres) GetEquationByType(ctx context.Context, equationType string) (domain.Equation, error) {
	if mock.GetEquationByTypeFunc == nil {
		panic("MockPostgres.GetEquationByTypeFunc: method is nil but Postgres.GetEquationByType was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		EquationType string
	}{
		Ctx:          ctx,
		EquationType: equationType,
	}
	mock.lockGetEquationByType.Lock()
	mock.calls.GetEquationByType = append(mock.calls.GetEquationByType, callInfo)
	mock.lockGetEquationByType.Unlock()
	return mock.GetEquationByTypeFunc(ctx, equationType)
}

// GetEquationByTypeCalls gets all the calls that were made to GetEquationByType.
// Check the length with:
//
//	len(mockedPostgres.GetEquationByTypeCalls())
func (mock *MockPostgres) GetEquationByTypeCalls() []struct {
	Ctx          context.Context
	EquationType string
} {
	var calls []struct {
		Ctx          context.Context
		EquationType string
	}
	mock.lockGetEquationByType.RLock()
	calls = mock.calls.GetEquationByType
	mock.lockGetEquationByType.RUnlock()
	return calls
}

// InTransaction calls InTransactionFunc.
func (mock *MockPostgres) InTransaction(ctx context.Context, inTx func(ctx context.Context) error) error {
	if mock.InTransactionFunc == nil {
		panic("MockPostgres.InTransactionFunc: method is nil but Postgres.InTransaction was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		InTx func(ctx context.Context) error
	}{
		Ctx:  ctx,
		InTx: inTx,
	}
	mock.lockInTransaction.Lock()
	mock.calls.InTransaction = append(mock.calls.InTransaction, callInfo)
	mock.lockInTransaction.Unlock()
	return mock.InTransactionFunc(ctx, inTx)
}

// InTransactionCalls gets all the calls that were made to InTransaction.
// Check the length with:
//
//	len(mockedPostgres.InTransactionCalls())
func (mock *MockPostgres) InTransactionCalls() []struct {
	Ctx  context.Context
	InTx func(ctx context.Context) error
} {
	var calls []struct {
		Ctx  context.Context
		InTx func(ctx context.Context) error
	}
	mock.lockInTransaction.RLock()
	calls = mock.calls.InTransaction
	mock.lockInTransaction.RUnlock()
	return calls
}

// PublishEvent calls PublishEventFunc.
func (mock *MockPostgres) PublishEvent(ctx context.Context, event domain.Event) (domain.Event, error) {
	if mock.PublishEventFunc == nil {
		panic("MockPostgres.PublishEventFunc: method is nil but Postgres.PublishEvent was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event domain.Event
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockPublishEvent.Lock()
	mock.calls.PublishEvent = append(mock.calls.PublishEvent, callInfo)
	mock.lockPublishEvent.Unlock()
	return mock.PublishEventFunc(ctx, event)
}

// PublishEventCalls gets all the calls that were made to PublishEvent.
// Check the length with:
//
//	len(mockedPostgres.PublishEventCalls())
func (mock *MockPostgres) PublishEventCalls() []struct {
	Ctx   context.Context
	Event domain.Event
} {
	var calls []struct {
		Ctx   context.Context
		Event domain.Event
	}
	mock.lockPublishEvent.RLock()
	calls = mock.calls.PublishEvent
	mock.lockPublishEvent.RUnlock()
	return calls
}

// Ensure that MockRedis does implement Redis.
// If this is not the case, regenerate this file with mockery.
var _ Redis = &MockRedis{}

// MockRedis is a mock implementation of Redis.
//
//	func TestSomethingThatUsesRedis(t *testing.T) {
//
//		// make and configure a mocked Redis
//		mockedRedis := &MockRedis{
//			DeleteFunc: func(ctx context.Context, idKey core.IdempotencyKey) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, idKey core.IdempotencyKey, target any) (core.IdempotencyStatus, error) {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(ctx context.Context, idKey core.IdempotencyKey, status core.IdempotencyStatus, value any) error {
//				panic("mock out the Set method")
//			},
//			TryLockFunc: func(ctx context.Context, idKey core.IdempotencyKey) (bool, error) {
//				panic("mock out the TryLock method")
//			},
//		}
//
//		// use mockedRedis in code that requires Redis
//		// and then make assertions.
//
//	}
type MockRedis struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, idKey core.IdempotencyKey) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, idKey core.IdempotencyKey, target any) (core.IdempotencyStatus, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, idKey core.IdempotencyKey, status core.IdempotencyStatus, value any) error

	// TryLockFunc mocks the TryLock method.
	TryLockFunc func(ctx context.Context, idKey core.IdempotencyKey) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IdKey is the idKey argument value.
			IdKey core.IdempotencyKey
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IdKey is the idKey argument value.
			IdKey core.IdempotencyKey
			// Target is the target argument value.
			Target any
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IdKey is the idKey argument value.
			IdKey core.IdempotencyKey
			// Status is the status argument value.
			Status core.IdempotencyStatus
			// Value is the value argument value.
			Value any
		}
		// TryLock holds details about calls to the TryLock method.
		TryLock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IdKey is the idKey argument value.
			IdKey core.IdempotencyKey
		}
	}
	lockDelete  sync.RWMutex
	lockGet     sync.RWMutex
	lockSet     sync.RWMutex
	lockTryLock sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *MockRedis) Delete(ctx context.Context, idKey core.IdempotencyKey) error {
	if mock.DeleteFunc == nil {
		panic("MockRedis.DeleteFunc: method is nil but Redis.Delete was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		IdKey core.IdempotencyKey
	}{
		Ctx:   ctx,
		IdKey: idKey,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, idKey)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedRedis.DeleteCalls())
func (mock *MockRedis) DeleteCalls() []struct {
	Ctx   context.Context
	IdKey core.IdempotencyKey
} {
	var calls []struct {
		Ctx   context.Context
		IdKey core.IdempotencyKey
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *MockRedis) Get(ctx context.Context, idKey core.IdempotencyKey, target any) (core.IdempotencyStatus, error) {
	if mock.GetFunc == nil {
		panic("MockRedis.GetFunc: method is nil but Redis.Get was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		IdKey  core.IdempotencyKey
		Target any
	}{
		Ctx:    ctx,
		IdKey:  idKey,
		Target: target,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, idKey, target)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRedis.GetCalls())
func (mock *MockRedis) GetCalls() []struct {
	Ctx    context.Context
	IdKey  core.IdempotencyKey
	Target any
} {
	var calls []struct {
		Ctx    context.Context
		IdKey  core.IdempotencyKey
		Target any
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *MockRedis) Set(ctx context.Context, idKey core.IdempotencyKey, status core.IdempotencyStatus, value any) error {
	if mock.SetFunc == nil {
		panic("MockRedis.SetFunc: method is nil but Redis.Set was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		IdKey  core.IdempotencyKey
		Status core.IdempotencyStatus
		Value  any
	}{
		Ctx:    ctx,
		IdKey:  idKey,
		Status: status,
		Value:  value,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, idKey, status, value)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedRedis.SetCalls())
func (mock *MockRedis) SetCalls() []struct {
	Ctx    context.Context
	IdKey  core.IdempotencyKey
	Status core.IdempotencyStatus
	Value  any
} {
	var calls []struct {
		Ctx    context.Context
		IdKey  core.IdempotencyKey
		Status core.IdempotencyStatus
		Value  any
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// TryLock calls TryLockFunc.
func (mock *MockRedis) TryLock(ctx context.Context, idKey core.IdempotencyKey) (bool, error) {
	if mock.TryLockFunc == nil {
		panic("MockRedis.TryLockFunc: method is nil but Redis.TryLock was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		IdKey core.IdempotencyKey
	}{
		Ctx:   ctx,
		IdKey: idKey,
	}
	mock.lockTryLock.Lock()
	mock.calls.TryLock = append(mock.calls.TryLock, callInfo)
	mock.lockTryLock.Unlock()
	return mock.TryLockFunc(ctx, idKey)
}

// TryLockCalls gets all the calls that were made to TryLock.
// Check the length with:
//
//	len(mockedRedis.TryLockCalls())
func (mock *MockRedis) TryLockCalls() []struct {
	Ctx   context.Context
	IdKey core.IdempotencyKey
} {
	var calls []struct {
		Ctx   context.Context
		IdKey core.IdempotencyKey
	}
	mock.lockTryLock.RLock()
	calls = mock.calls.TryLock
	mock.lockTryLock.RUnlock()
	return calls
}
