// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package create_task

import (
	"context"
	"pinnAutomizer/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgres creates a new instance of MockPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgres {
	mock := &MockPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgres is an autogenerated mock type for the Postgres type
type MockPostgres struct {
	mock.Mock
}

type MockPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgres) EXPECT() *MockPostgres_Expecter {
	return &MockPostgres_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function for the type MockPostgres
func (_mock *MockPostgres) CreateTask(ctx context.Context, task domain.Task) (domain.Task, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) (domain.Task, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) domain.Task); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockPostgres_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task domain.Task
func (_e *MockPostgres_Expecter) CreateTask(ctx interface{}, task interface{}) *MockPostgres_CreateTask_Call {
	return &MockPostgres_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *MockPostgres_CreateTask_Call) Run(run func(ctx context.Context, task domain.Task)) *MockPostgres_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Task
		if args[1] != nil {
			arg1 = args[1].(domain.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_CreateTask_Call) Return(task1 domain.Task, err error) *MockPostgres_CreateTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockPostgres_CreateTask_Call) RunAndReturn(run func(ctx context.Context, task domain.Task) (domain.Task, error)) *MockPostgres_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetEquationByType provides a mock function for the type MockPostgres
func (_mock *MockPostgres) GetEquationByType(ctx context.Context, equationType string) (domain.Equation, error) {
	ret := _mock.Called(ctx, equationType)

	if len(ret) == 0 {
		panic("no return value specified for GetEquationByType")
	}

	var r0 domain.Equation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Equation, error)); ok {
		return returnFunc(ctx, equationType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Equation); ok {
		r0 = returnFunc(ctx, equationType)
	} else {
		r0 = ret.Get(0).(domain.Equation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, equationType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_GetEquationByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEquationByType'
type MockPostgres_GetEquationByType_Call struct {
	*mock.Call
}

// GetEquationByType is a helper method to define mock.On call
//   - ctx context.Context
//   - equationType string
func (_e *MockPostgres_Expecter) GetEquationByType(ctx interface{}, equationType interface{}) *MockPostgres_GetEquationByType_Call {
	return &MockPostgres_GetEquationByType_Call{Call: _e.mock.On("GetEquationByType", ctx, equationType)}
}

func (_c *MockPostgres_GetEquationByType_Call) Run(run func(ctx context.Context, equationType string)) *MockPostgres_GetEquationByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_GetEquationByType_Call) Return(equation domain.Equation, err error) *MockPostgres_GetEquationByType_Call {
	_c.Call.Return(equation, err)
	return _c
}

func (_c *MockPostgres_GetEquationByType_Call) RunAndReturn(run func(ctx context.Context, equationType string) (domain.Equation, error)) *MockPostgres_GetEquationByType_Call {
	_c.Call.Return(run)
	return _c
}

// PublishEvent provides a mock function for the type MockPostgres
func (_mock *MockPostgres) PublishEvent(ctx context.Context, event domain.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_PublishEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishEvent'
type MockPostgres_PublishEvent_Call struct {
	*mock.Call
}

// PublishEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.Event
func (_e *MockPostgres_Expecter) PublishEvent(ctx interface{}, event interface{}) *MockPostgres_PublishEvent_Call {
	return &MockPostgres_PublishEvent_Call{Call: _e.mock.On("PublishEvent", ctx, event)}
}

func (_c *MockPostgres_PublishEvent_Call) Run(run func(ctx context.Context, event domain.Event)) *MockPostgres_PublishEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Event
		if args[1] != nil {
			arg1 = args[1].(domain.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_PublishEvent_Call) Return(err error) *MockPostgres_PublishEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_PublishEvent_Call) RunAndReturn(run func(ctx context.Context, event domain.Event) error) *MockPostgres_PublishEvent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaskStatusByID provides a mock function for the type MockPostgres
func (_mock *MockPostgres) UpdateTaskStatusByID(ctx context.Context, id uuid.UUID, status string) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskStatusByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_UpdateTaskStatusByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskStatusByID'
type MockPostgres_UpdateTaskStatusByID_Call struct {
	*mock.Call
}

// UpdateTaskStatusByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status string
func (_e *MockPostgres_Expecter) UpdateTaskStatusByID(ctx interface{}, id interface{}, status interface{}) *MockPostgres_UpdateTaskStatusByID_Call {
	return &MockPostgres_UpdateTaskStatusByID_Call{Call: _e.mock.On("UpdateTaskStatusByID", ctx, id, status)}
}

func (_c *MockPostgres_UpdateTaskStatusByID_Call) Run(run func(ctx context.Context, id uuid.UUID, status string)) *MockPostgres_UpdateTaskStatusByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostgres_UpdateTaskStatusByID_Call) Return(err error) *MockPostgres_UpdateTaskStatusByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_UpdateTaskStatusByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status string) error) *MockPostgres_UpdateTaskStatusByID_Call {
	_c.Call.Return(run)
	return _c
}

// Wrap provides a mock function for the type MockPostgres
func (_mock *MockPostgres) Wrap(ctx context.Context, fn func(context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Wrap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_Wrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wrap'
type MockPostgres_Wrap_Call struct {
	*mock.Call
}

// Wrap is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *MockPostgres_Expecter) Wrap(ctx interface{}, fn interface{}) *MockPostgres_Wrap_Call {
	return &MockPostgres_Wrap_Call{Call: _e.mock.On("Wrap", ctx, fn)}
}

func (_c *MockPostgres_Wrap_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *MockPostgres_Wrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_Wrap_Call) Return(err error) *MockPostgres_Wrap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_Wrap_Call) RunAndReturn(run func(ctx context.Context, fn func(context.Context) error) error) *MockPostgres_Wrap_Call {
	_c.Call.Return(run)
	return _c
}
