// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package solve_task

import (
	"context"
	"pinnAutomizer/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgres creates a new instance of MockPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgres {
	mock := &MockPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgres is an autogenerated mock type for the Postgres type
type MockPostgres struct {
	mock.Mock
}

type MockPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgres) EXPECT() *MockPostgres_Expecter {
	return &MockPostgres_Expecter{mock: &_m.Mock}
}

// GetTaskByIDAndUserID provides a mock function for the type MockPostgres
func (_mock *MockPostgres) GetTaskByIDAndUserID(ctx context.Context, id uuid.UUID, userID uuid.UUID) (domain.Task, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByIDAndUserID")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.Task, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.Task); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_GetTaskByIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByIDAndUserID'
type MockPostgres_GetTaskByIDAndUserID_Call struct {
	*mock.Call
}

// GetTaskByIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockPostgres_Expecter) GetTaskByIDAndUserID(ctx interface{}, id interface{}, userID interface{}) *MockPostgres_GetTaskByIDAndUserID_Call {
	return &MockPostgres_GetTaskByIDAndUserID_Call{Call: _e.mock.On("GetTaskByIDAndUserID", ctx, id, userID)}
}

func (_c *MockPostgres_GetTaskByIDAndUserID_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockPostgres_GetTaskByIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostgres_GetTaskByIDAndUserID_Call) Return(task domain.Task, err error) *MockPostgres_GetTaskByIDAndUserID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockPostgres_GetTaskByIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (domain.Task, error)) *MockPostgres_GetTaskByIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// PublishEvent provides a mock function for the type MockPostgres
func (_mock *MockPostgres) PublishEvent(ctx context.Context, event domain.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_PublishEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishEvent'
type MockPostgres_PublishEvent_Call struct {
	*mock.Call
}

// PublishEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.Event
func (_e *MockPostgres_Expecter) PublishEvent(ctx interface{}, event interface{}) *MockPostgres_PublishEvent_Call {
	return &MockPostgres_PublishEvent_Call{Call: _e.mock.On("PublishEvent", ctx, event)}
}

func (_c *MockPostgres_PublishEvent_Call) Run(run func(ctx context.Context, event domain.Event)) *MockPostgres_PublishEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Event
		if args[1] != nil {
			arg1 = args[1].(domain.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_PublishEvent_Call) Return(err error) *MockPostgres_PublishEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_PublishEvent_Call) RunAndReturn(run func(ctx context.Context, event domain.Event) error) *MockPostgres_PublishEvent_Call {
	_c.Call.Return(run)
	return _c
}
