// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package authMe

import (
	"context"
	"sync"

	"github.com/AridanWarlock/pinnAutomizer/internal/domain"
	"github.com/google/uuid"
)

// Ensure that MockUsecase does implement Usecase.
// If this is not the case, regenerate this file with mockery.
var _ Usecase = &MockUsecase{}

// MockUsecase is a mock implementation of Usecase.
//
//	func TestSomethingThatUsesUsecase(t *testing.T) {
//
//		// make and configure a mocked Usecase
//		mockedUsecase := &MockUsecase{
//			MeFunc: func(ctx context.Context) (Output, error) {
//				panic("mock out the Me method")
//			},
//		}
//
//		// use mockedUsecase in code that requires Usecase
//		// and then make assertions.
//
//	}
type MockUsecase struct {
	// MeFunc mocks the Me method.
	MeFunc func(ctx context.Context) (Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// Me holds details about calls to the Me method.
		Me []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockMe sync.RWMutex
}

// Me calls MeFunc.
func (mock *MockUsecase) Me(ctx context.Context) (Output, error) {
	if mock.MeFunc == nil {
		panic("MockUsecase.MeFunc: method is nil but Usecase.Me was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockMe.Lock()
	mock.calls.Me = append(mock.calls.Me, callInfo)
	mock.lockMe.Unlock()
	return mock.MeFunc(ctx)
}

// MeCalls gets all the calls that were made to Me.
// Check the length with:
//
//	len(mockedUsecase.MeCalls())
func (mock *MockUsecase) MeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockMe.RLock()
	calls = mock.calls.Me
	mock.lockMe.RUnlock()
	return calls
}

// Ensure that MockPostgres does implement Postgres.
// If this is not the case, regenerate this file with mockery.
var _ Postgres = &MockPostgres{}

// MockPostgres is a mock implementation of Postgres.
//
//	func TestSomethingThatUsesPostgres(t *testing.T) {
//
//		// make and configure a mocked Postgres
//		mockedPostgres := &MockPostgres{
//			GetUserByIDFunc: func(ctx context.Context, id uuid.UUID) (domain.User, error) {
//				panic("mock out the GetUserByID method")
//			},
//		}
//
//		// use mockedPostgres in code that requires Postgres
//		// and then make assertions.
//
//	}
type MockPostgres struct {
	// GetUserByIDFunc mocks the GetUserByID method.
	GetUserByIDFunc func(ctx context.Context, id uuid.UUID) (domain.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetUserByID holds details about calls to the GetUserByID method.
		GetUserByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockGetUserByID sync.RWMutex
}

// GetUserByID calls GetUserByIDFunc.
func (mock *MockPostgres) GetUserByID(ctx context.Context, id uuid.UUID) (domain.User, error) {
	if mock.GetUserByIDFunc == nil {
		panic("MockPostgres.GetUserByIDFunc: method is nil but Postgres.GetUserByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetUserByID.Lock()
	mock.calls.GetUserByID = append(mock.calls.GetUserByID, callInfo)
	mock.lockGetUserByID.Unlock()
	return mock.GetUserByIDFunc(ctx, id)
}

// GetUserByIDCalls gets all the calls that were made to GetUserByID.
// Check the length with:
//
//	len(mockedPostgres.GetUserByIDCalls())
func (mock *MockPostgres) GetUserByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetUserByID.RLock()
	calls = mock.calls.GetUserByID
	mock.lockGetUserByID.RUnlock()
	return calls
}
