// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package poolx

import (
	"context"
	"sync"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Ensure that mockexecutor does implement executor.
// If this is not the case, regenerate this file with mockery.
var _ executor = &mockexecutor{}

// mockexecutor is a mock implementation of executor.
//
//	func TestSomethingThatUsesexecutor(t *testing.T) {
//
//		// make and configure a mocked executor
//		mockedexecutor := &mockexecutor{
//			ExecFunc: func(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
//				panic("mock out the Exec method")
//			},
//			QueryFunc: func(ctx context.Context, query string, args ...any) (pgx.Rows, error) {
//				panic("mock out the Query method")
//			},
//		}
//
//		// use mockedexecutor in code that requires executor
//		// and then make assertions.
//
//	}
type mockexecutor struct {
	// ExecFunc mocks the Exec method.
	ExecFunc func(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)

	// QueryFunc mocks the Query method.
	QueryFunc func(ctx context.Context, query string, args ...any) (pgx.Rows, error)

	// calls tracks calls to the methods.
	calls struct {
		// Exec holds details about calls to the Exec method.
		Exec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SQL is the sql argument value.
			SQL string
			// Arguments is the arguments argument value.
			Arguments []any
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
	}
	lockExec  sync.RWMutex
	lockQuery sync.RWMutex
}

// Exec calls ExecFunc.
func (mock *mockexecutor) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	if mock.ExecFunc == nil {
		panic("mockexecutor.ExecFunc: method is nil but executor.Exec was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		SQL       string
		Arguments []any
	}{
		Ctx:       ctx,
		SQL:       sql,
		Arguments: arguments,
	}
	mock.lockExec.Lock()
	mock.calls.Exec = append(mock.calls.Exec, callInfo)
	mock.lockExec.Unlock()
	return mock.ExecFunc(ctx, sql, arguments...)
}

// ExecCalls gets all the calls that were made to Exec.
// Check the length with:
//
//	len(mockedexecutor.ExecCalls())
func (mock *mockexecutor) ExecCalls() []struct {
	Ctx       context.Context
	SQL       string
	Arguments []any
} {
	var calls []struct {
		Ctx       context.Context
		SQL       string
		Arguments []any
	}
	mock.lockExec.RLock()
	calls = mock.calls.Exec
	mock.lockExec.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *mockexecutor) Query(ctx context.Context, query string, args ...any) (pgx.Rows, error) {
	if mock.QueryFunc == nil {
		panic("mockexecutor.QueryFunc: method is nil but executor.Query was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Query: query,
		Args:  args,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(ctx, query, args...)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedexecutor.QueryCalls())
func (mock *mockexecutor) QueryCalls() []struct {
	Ctx   context.Context
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Args  []any
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}
