// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package authRegister

import (
	"context"
	"sync"

	"github.com/AridanWarlock/pinnAutomizer/pinn/internal/domain"
	"github.com/AridanWarlock/pinnAutomizer/pkg/core"
)

// Ensure that MockUsecase does implement Usecase.
// If this is not the case, regenerate this file with mockery.
var _ Usecase = &MockUsecase{}

// MockUsecase is a mock implementation of Usecase.
//
//	func TestSomethingThatUsesUsecase(t *testing.T) {
//
//		// make and configure a mocked Usecase
//		mockedUsecase := &MockUsecase{
//			RegisterFunc: func(ctx context.Context, in Input) (Output, error) {
//				panic("mock out the Register method")
//			},
//		}
//
//		// use mockedUsecase in code that requires Usecase
//		// and then make assertions.
//
//	}
type MockUsecase struct {
	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, in Input) (Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In Input
		}
	}
	lockRegister sync.RWMutex
}

// Register calls RegisterFunc.
func (mock *MockUsecase) Register(ctx context.Context, in Input) (Output, error) {
	if mock.RegisterFunc == nil {
		panic("MockUsecase.RegisterFunc: method is nil but Usecase.Register was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  Input
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(ctx, in)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedUsecase.RegisterCalls())
func (mock *MockUsecase) RegisterCalls() []struct {
	Ctx context.Context
	In  Input
} {
	var calls []struct {
		Ctx context.Context
		In  Input
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}

// Ensure that MockPostgres does implement Postgres.
// If this is not the case, regenerate this file with mockery.
var _ Postgres = &MockPostgres{}

// MockPostgres is a mock implementation of Postgres.
//
//	func TestSomethingThatUsesPostgres(t *testing.T) {
//
//		// make and configure a mocked Postgres
//		mockedPostgres := &MockPostgres{
//			CreateUserFunc: func(ctx context.Context, user domain.User) (domain.User, error) {
//				panic("mock out the CreateUser method")
//			},
//			CreateUsersRolesBatchFunc: func(ctx context.Context, usersRoles []domain.UsersRoles) ([]domain.UsersRoles, error) {
//				panic("mock out the CreateUsersRolesBatch method")
//			},
//			GetRoleByTitleFunc: func(ctx context.Context, title string) (core.Role, error) {
//				panic("mock out the GetRoleByTitle method")
//			},
//			InTransactionFunc: func(ctx context.Context, inTx func(ctx context.Context) error) error {
//				panic("mock out the InTransaction method")
//			},
//		}
//
//		// use mockedPostgres in code that requires Postgres
//		// and then make assertions.
//
//	}
type MockPostgres struct {
	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, user domain.User) (domain.User, error)

	// CreateUsersRolesBatchFunc mocks the CreateUsersRolesBatch method.
	CreateUsersRolesBatchFunc func(ctx context.Context, usersRoles []domain.UsersRoles) ([]domain.UsersRoles, error)

	// GetRoleByTitleFunc mocks the GetRoleByTitle method.
	GetRoleByTitleFunc func(ctx context.Context, title string) (core.Role, error)

	// InTransactionFunc mocks the InTransaction method.
	InTransactionFunc func(ctx context.Context, inTx func(ctx context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User domain.User
		}
		// CreateUsersRolesBatch holds details about calls to the CreateUsersRolesBatch method.
		CreateUsersRolesBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UsersRoles is the usersRoles argument value.
			UsersRoles []domain.UsersRoles
		}
		// GetRoleByTitle holds details about calls to the GetRoleByTitle method.
		GetRoleByTitle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Title is the title argument value.
			Title string
		}
		// InTransaction holds details about calls to the InTransaction method.
		InTransaction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InTx is the inTx argument value.
			InTx func(ctx context.Context) error
		}
	}
	lockCreateUser            sync.RWMutex
	lockCreateUsersRolesBatch sync.RWMutex
	lockGetRoleByTitle        sync.RWMutex
	lockInTransaction         sync.RWMutex
}

// CreateUser calls CreateUserFunc.
func (mock *MockPostgres) CreateUser(ctx context.Context, user domain.User) (domain.User, error) {
	if mock.CreateUserFunc == nil {
		panic("MockPostgres.CreateUserFunc: method is nil but Postgres.CreateUser was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User domain.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(ctx, user)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedPostgres.CreateUserCalls())
func (mock *MockPostgres) CreateUserCalls() []struct {
	Ctx  context.Context
	User domain.User
} {
	var calls []struct {
		Ctx  context.Context
		User domain.User
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// CreateUsersRolesBatch calls CreateUsersRolesBatchFunc.
func (mock *MockPostgres) CreateUsersRolesBatch(ctx context.Context, usersRoles []domain.UsersRoles) ([]domain.UsersRoles, error) {
	if mock.CreateUsersRolesBatchFunc == nil {
		panic("MockPostgres.CreateUsersRolesBatchFunc: method is nil but Postgres.CreateUsersRolesBatch was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		UsersRoles []domain.UsersRoles
	}{
		Ctx:        ctx,
		UsersRoles: usersRoles,
	}
	mock.lockCreateUsersRolesBatch.Lock()
	mock.calls.CreateUsersRolesBatch = append(mock.calls.CreateUsersRolesBatch, callInfo)
	mock.lockCreateUsersRolesBatch.Unlock()
	return mock.CreateUsersRolesBatchFunc(ctx, usersRoles)
}

// CreateUsersRolesBatchCalls gets all the calls that were made to CreateUsersRolesBatch.
// Check the length with:
//
//	len(mockedPostgres.CreateUsersRolesBatchCalls())
func (mock *MockPostgres) CreateUsersRolesBatchCalls() []struct {
	Ctx        context.Context
	UsersRoles []domain.UsersRoles
} {
	var calls []struct {
		Ctx        context.Context
		UsersRoles []domain.UsersRoles
	}
	mock.lockCreateUsersRolesBatch.RLock()
	calls = mock.calls.CreateUsersRolesBatch
	mock.lockCreateUsersRolesBatch.RUnlock()
	return calls
}

// GetRoleByTitle calls GetRoleByTitleFunc.
func (mock *MockPostgres) GetRoleByTitle(ctx context.Context, title string) (core.Role, error) {
	if mock.GetRoleByTitleFunc == nil {
		panic("MockPostgres.GetRoleByTitleFunc: method is nil but Postgres.GetRoleByTitle was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Title string
	}{
		Ctx:   ctx,
		Title: title,
	}
	mock.lockGetRoleByTitle.Lock()
	mock.calls.GetRoleByTitle = append(mock.calls.GetRoleByTitle, callInfo)
	mock.lockGetRoleByTitle.Unlock()
	return mock.GetRoleByTitleFunc(ctx, title)
}

// GetRoleByTitleCalls gets all the calls that were made to GetRoleByTitle.
// Check the length with:
//
//	len(mockedPostgres.GetRoleByTitleCalls())
func (mock *MockPostgres) GetRoleByTitleCalls() []struct {
	Ctx   context.Context
	Title string
} {
	var calls []struct {
		Ctx   context.Context
		Title string
	}
	mock.lockGetRoleByTitle.RLock()
	calls = mock.calls.GetRoleByTitle
	mock.lockGetRoleByTitle.RUnlock()
	return calls
}

// InTransaction calls InTransactionFunc.
func (mock *MockPostgres) InTransaction(ctx context.Context, inTx func(ctx context.Context) error) error {
	if mock.InTransactionFunc == nil {
		panic("MockPostgres.InTransactionFunc: method is nil but Postgres.InTransaction was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		InTx func(ctx context.Context) error
	}{
		Ctx:  ctx,
		InTx: inTx,
	}
	mock.lockInTransaction.Lock()
	mock.calls.InTransaction = append(mock.calls.InTransaction, callInfo)
	mock.lockInTransaction.Unlock()
	return mock.InTransactionFunc(ctx, inTx)
}

// InTransactionCalls gets all the calls that were made to InTransaction.
// Check the length with:
//
//	len(mockedPostgres.InTransactionCalls())
func (mock *MockPostgres) InTransactionCalls() []struct {
	Ctx  context.Context
	InTx func(ctx context.Context) error
} {
	var calls []struct {
		Ctx  context.Context
		InTx func(ctx context.Context) error
	}
	mock.lockInTransaction.RLock()
	calls = mock.calls.InTransaction
	mock.lockInTransaction.RUnlock()
	return calls
}

// Ensure that MockPasswordHasher does implement PasswordHasher.
// If this is not the case, regenerate this file with mockery.
var _ PasswordHasher = &MockPasswordHasher{}

// MockPasswordHasher is a mock implementation of PasswordHasher.
//
//	func TestSomethingThatUsesPasswordHasher(t *testing.T) {
//
//		// make and configure a mocked PasswordHasher
//		mockedPasswordHasher := &MockPasswordHasher{
//			HashPasswordFunc: func(password string) (string, error) {
//				panic("mock out the HashPassword method")
//			},
//		}
//
//		// use mockedPasswordHasher in code that requires PasswordHasher
//		// and then make assertions.
//
//	}
type MockPasswordHasher struct {
	// HashPasswordFunc mocks the HashPassword method.
	HashPasswordFunc func(password string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// HashPassword holds details about calls to the HashPassword method.
		HashPassword []struct {
			// Password is the password argument value.
			Password string
		}
	}
	lockHashPassword sync.RWMutex
}

// HashPassword calls HashPasswordFunc.
func (mock *MockPasswordHasher) HashPassword(password string) (string, error) {
	if mock.HashPasswordFunc == nil {
		panic("MockPasswordHasher.HashPasswordFunc: method is nil but PasswordHasher.HashPassword was just called")
	}
	callInfo := struct {
		Password string
	}{
		Password: password,
	}
	mock.lockHashPassword.Lock()
	mock.calls.HashPassword = append(mock.calls.HashPassword, callInfo)
	mock.lockHashPassword.Unlock()
	return mock.HashPasswordFunc(password)
}

// HashPasswordCalls gets all the calls that were made to HashPassword.
// Check the length with:
//
//	len(mockedPasswordHasher.HashPasswordCalls())
func (mock *MockPasswordHasher) HashPasswordCalls() []struct {
	Password string
} {
	var calls []struct {
		Password string
	}
	mock.lockHashPassword.RLock()
	calls = mock.calls.HashPassword
	mock.lockHashPassword.RUnlock()
	return calls
}
