// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package register

import (
	"context"
	"pinnAutomizer/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgres creates a new instance of MockPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgres {
	mock := &MockPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgres is an autogenerated mock type for the Postgres type
type MockPostgres struct {
	mock.Mock
}

type MockPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgres) EXPECT() *MockPostgres_Expecter {
	return &MockPostgres_Expecter{mock: &_m.Mock}
}

// CreateAuthToken provides a mock function for the type MockPostgres
func (_mock *MockPostgres) CreateAuthToken(ctx context.Context, userID uuid.UUID) (domain.AuthToken, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthToken")
	}

	var r0 domain.AuthToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.AuthToken, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.AuthToken); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.AuthToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_CreateAuthToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthToken'
type MockPostgres_CreateAuthToken_Call struct {
	*mock.Call
}

// CreateAuthToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPostgres_Expecter) CreateAuthToken(ctx interface{}, userID interface{}) *MockPostgres_CreateAuthToken_Call {
	return &MockPostgres_CreateAuthToken_Call{Call: _e.mock.On("CreateAuthToken", ctx, userID)}
}

func (_c *MockPostgres_CreateAuthToken_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPostgres_CreateAuthToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_CreateAuthToken_Call) Return(authToken domain.AuthToken, err error) *MockPostgres_CreateAuthToken_Call {
	_c.Call.Return(authToken, err)
	return _c
}

func (_c *MockPostgres_CreateAuthToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (domain.AuthToken, error)) *MockPostgres_CreateAuthToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockPostgres
func (_mock *MockPostgres) CreateUser(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockPostgres_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockPostgres_Expecter) CreateUser(ctx interface{}, user interface{}) *MockPostgres_CreateUser_Call {
	return &MockPostgres_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockPostgres_CreateUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockPostgres_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_CreateUser_Call) Return(user1 domain.User, err error) *MockPostgres_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockPostgres_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (domain.User, error)) *MockPostgres_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUsersRolesBatch provides a mock function for the type MockPostgres
func (_mock *MockPostgres) CreateUsersRolesBatch(ctx context.Context, usersRoles []domain.UsersRoles) ([]domain.UsersRoles, error) {
	ret := _mock.Called(ctx, usersRoles)

	if len(ret) == 0 {
		panic("no return value specified for CreateUsersRolesBatch")
	}

	var r0 []domain.UsersRoles
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.UsersRoles) ([]domain.UsersRoles, error)); ok {
		return returnFunc(ctx, usersRoles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.UsersRoles) []domain.UsersRoles); ok {
		r0 = returnFunc(ctx, usersRoles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UsersRoles)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.UsersRoles) error); ok {
		r1 = returnFunc(ctx, usersRoles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_CreateUsersRolesBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUsersRolesBatch'
type MockPostgres_CreateUsersRolesBatch_Call struct {
	*mock.Call
}

// CreateUsersRolesBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - usersRoles []domain.UsersRoles
func (_e *MockPostgres_Expecter) CreateUsersRolesBatch(ctx interface{}, usersRoles interface{}) *MockPostgres_CreateUsersRolesBatch_Call {
	return &MockPostgres_CreateUsersRolesBatch_Call{Call: _e.mock.On("CreateUsersRolesBatch", ctx, usersRoles)}
}

func (_c *MockPostgres_CreateUsersRolesBatch_Call) Run(run func(ctx context.Context, usersRoles []domain.UsersRoles)) *MockPostgres_CreateUsersRolesBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.UsersRoles
		if args[1] != nil {
			arg1 = args[1].([]domain.UsersRoles)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_CreateUsersRolesBatch_Call) Return(usersRoless []domain.UsersRoles, err error) *MockPostgres_CreateUsersRolesBatch_Call {
	_c.Call.Return(usersRoless, err)
	return _c
}

func (_c *MockPostgres_CreateUsersRolesBatch_Call) RunAndReturn(run func(ctx context.Context, usersRoles []domain.UsersRoles) ([]domain.UsersRoles, error)) *MockPostgres_CreateUsersRolesBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleByTitle provides a mock function for the type MockPostgres
func (_mock *MockPostgres) GetRoleByTitle(ctx context.Context, title string) (domain.Role, error) {
	ret := _mock.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleByTitle")
	}

	var r0 domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Role, error)); ok {
		return returnFunc(ctx, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Role); ok {
		r0 = returnFunc(ctx, title)
	} else {
		r0 = ret.Get(0).(domain.Role)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_GetRoleByTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleByTitle'
type MockPostgres_GetRoleByTitle_Call struct {
	*mock.Call
}

// GetRoleByTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
func (_e *MockPostgres_Expecter) GetRoleByTitle(ctx interface{}, title interface{}) *MockPostgres_GetRoleByTitle_Call {
	return &MockPostgres_GetRoleByTitle_Call{Call: _e.mock.On("GetRoleByTitle", ctx, title)}
}

func (_c *MockPostgres_GetRoleByTitle_Call) Run(run func(ctx context.Context, title string)) *MockPostgres_GetRoleByTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_GetRoleByTitle_Call) Return(role domain.Role, err error) *MockPostgres_GetRoleByTitle_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockPostgres_GetRoleByTitle_Call) RunAndReturn(run func(ctx context.Context, title string) (domain.Role, error)) *MockPostgres_GetRoleByTitle_Call {
	_c.Call.Return(run)
	return _c
}

// Wrap provides a mock function for the type MockPostgres
func (_mock *MockPostgres) Wrap(ctx context.Context, fn func(context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Wrap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_Wrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wrap'
type MockPostgres_Wrap_Call struct {
	*mock.Call
}

// Wrap is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *MockPostgres_Expecter) Wrap(ctx interface{}, fn interface{}) *MockPostgres_Wrap_Call {
	return &MockPostgres_Wrap_Call{Call: _e.mock.On("Wrap", ctx, fn)}
}

func (_c *MockPostgres_Wrap_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *MockPostgres_Wrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_Wrap_Call) Return(err error) *MockPostgres_Wrap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_Wrap_Call) RunAndReturn(run func(ctx context.Context, fn func(context.Context) error) error) *MockPostgres_Wrap_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordHasher creates a new instance of MockPasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordHasher {
	mock := &MockPasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordHasher is an autogenerated mock type for the PasswordHasher type
type MockPasswordHasher struct {
	mock.Mock
}

type MockPasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordHasher) EXPECT() *MockPasswordHasher_Expecter {
	return &MockPasswordHasher_Expecter{mock: &_m.Mock}
}

// HashPassword provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) HashPassword(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordHasher_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockPasswordHasher_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordHasher_Expecter) HashPassword(password interface{}) *MockPasswordHasher_HashPassword_Call {
	return &MockPasswordHasher_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockPasswordHasher_HashPassword_Call) Run(run func(password string)) *MockPasswordHasher_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPasswordHasher_HashPassword_Call) Return(s string, err error) *MockPasswordHasher_HashPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPasswordHasher_HashPassword_Call) RunAndReturn(run func(password string) (string, error)) *MockPasswordHasher_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}
