// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package core

import (
	"sync"
)

// Ensure that MockToHeadersSerializable does implement ToHeadersSerializable.
// If this is not the case, regenerate this file with mockery.
var _ ToHeadersSerializable = &MockToHeadersSerializable{}

// MockToHeadersSerializable is a mock implementation of ToHeadersSerializable.
//
//	func TestSomethingThatUsesToHeadersSerializable(t *testing.T) {
//
//		// make and configure a mocked ToHeadersSerializable
//		mockedToHeadersSerializable := &MockToHeadersSerializable{
//			ToHeadersFunc: func() map[string]string {
//				panic("mock out the ToHeaders method")
//			},
//		}
//
//		// use mockedToHeadersSerializable in code that requires ToHeadersSerializable
//		// and then make assertions.
//
//	}
type MockToHeadersSerializable struct {
	// ToHeadersFunc mocks the ToHeaders method.
	ToHeadersFunc func() map[string]string

	// calls tracks calls to the methods.
	calls struct {
		// ToHeaders holds details about calls to the ToHeaders method.
		ToHeaders []struct {
		}
	}
	lockToHeaders sync.RWMutex
}

// ToHeaders calls ToHeadersFunc.
func (mock *MockToHeadersSerializable) ToHeaders() map[string]string {
	if mock.ToHeadersFunc == nil {
		panic("MockToHeadersSerializable.ToHeadersFunc: method is nil but ToHeadersSerializable.ToHeaders was just called")
	}
	callInfo := struct {
	}{}
	mock.lockToHeaders.Lock()
	mock.calls.ToHeaders = append(mock.calls.ToHeaders, callInfo)
	mock.lockToHeaders.Unlock()
	return mock.ToHeadersFunc()
}

// ToHeadersCalls gets all the calls that were made to ToHeaders.
// Check the length with:
//
//	len(mockedToHeadersSerializable.ToHeadersCalls())
func (mock *MockToHeadersSerializable) ToHeadersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockToHeaders.RLock()
	calls = mock.calls.ToHeaders
	mock.lockToHeaders.RUnlock()
	return calls
}
