// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package middleware

import (
	"context"
	"sync"

	"github.com/AridanWarlock/pinnAutomizer/pkg/core"
)

// Ensure that MockTokenParser does implement TokenParser.
// If this is not the case, regenerate this file with mockery.
var _ TokenParser = &MockTokenParser{}

// MockTokenParser is a mock implementation of TokenParser.
//
//	func TestSomethingThatUsesTokenParser(t *testing.T) {
//
//		// make and configure a mocked TokenParser
//		mockedTokenParser := &MockTokenParser{
//			GetClaimsFunc: func(token core.AccessToken) (core.JwtClaims, error) {
//				panic("mock out the GetClaims method")
//			},
//		}
//
//		// use mockedTokenParser in code that requires TokenParser
//		// and then make assertions.
//
//	}
type MockTokenParser struct {
	// GetClaimsFunc mocks the GetClaims method.
	GetClaimsFunc func(token core.AccessToken) (core.JwtClaims, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetClaims holds details about calls to the GetClaims method.
		GetClaims []struct {
			// Token is the token argument value.
			Token core.AccessToken
		}
	}
	lockGetClaims sync.RWMutex
}

// GetClaims calls GetClaimsFunc.
func (mock *MockTokenParser) GetClaims(token core.AccessToken) (core.JwtClaims, error) {
	if mock.GetClaimsFunc == nil {
		panic("MockTokenParser.GetClaimsFunc: method is nil but TokenParser.GetClaims was just called")
	}
	callInfo := struct {
		Token core.AccessToken
	}{
		Token: token,
	}
	mock.lockGetClaims.Lock()
	mock.calls.GetClaims = append(mock.calls.GetClaims, callInfo)
	mock.lockGetClaims.Unlock()
	return mock.GetClaimsFunc(token)
}

// GetClaimsCalls gets all the calls that were made to GetClaims.
// Check the length with:
//
//	len(mockedTokenParser.GetClaimsCalls())
func (mock *MockTokenParser) GetClaimsCalls() []struct {
	Token core.AccessToken
} {
	var calls []struct {
		Token core.AccessToken
	}
	mock.lockGetClaims.RLock()
	calls = mock.calls.GetClaims
	mock.lockGetClaims.RUnlock()
	return calls
}

// Ensure that MockRedis does implement Redis.
// If this is not the case, regenerate this file with mockery.
var _ Redis = &MockRedis{}

// MockRedis is a mock implementation of Redis.
//
//	func TestSomethingThatUsesRedis(t *testing.T) {
//
//		// make and configure a mocked Redis
//		mockedRedis := &MockRedis{
//			GetFunc: func(ctx context.Context, key string, target any) error {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedRedis in code that requires Redis
//		// and then make assertions.
//
//	}
type MockRedis struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string, target any) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Target is the target argument value.
			Target any
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *MockRedis) Get(ctx context.Context, key string, target any) error {
	if mock.GetFunc == nil {
		panic("MockRedis.GetFunc: method is nil but Redis.Get was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Key    string
		Target any
	}{
		Ctx:    ctx,
		Key:    key,
		Target: target,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key, target)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRedis.GetCalls())
func (mock *MockRedis) GetCalls() []struct {
	Ctx    context.Context
	Key    string
	Target any
} {
	var calls []struct {
		Ctx    context.Context
		Key    string
		Target any
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
