// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package tasksGet

import (
	"context"
	"sync"

	"github.com/AridanWarlock/pinnAutomizer/tasks/internal/domain"
	"github.com/google/uuid"
)

// Ensure that MockUsecase does implement Usecase.
// If this is not the case, regenerate this file with mockery.
var _ Usecase = &MockUsecase{}

// MockUsecase is a mock implementation of Usecase.
//
//	func TestSomethingThatUsesUsecase(t *testing.T) {
//
//		// make and configure a mocked Usecase
//		mockedUsecase := &MockUsecase{
//			GetTasksFunc: func(ctx context.Context, in Input) (Output, error) {
//				panic("mock out the GetTasks method")
//			},
//		}
//
//		// use mockedUsecase in code that requires Usecase
//		// and then make assertions.
//
//	}
type MockUsecase struct {
	// GetTasksFunc mocks the GetTasks method.
	GetTasksFunc func(ctx context.Context, in Input) (Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetTasks holds details about calls to the GetTasks method.
		GetTasks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In Input
		}
	}
	lockGetTasks sync.RWMutex
}

// GetTasks calls GetTasksFunc.
func (mock *MockUsecase) GetTasks(ctx context.Context, in Input) (Output, error) {
	if mock.GetTasksFunc == nil {
		panic("MockUsecase.GetTasksFunc: method is nil but Usecase.GetTasks was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  Input
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockGetTasks.Lock()
	mock.calls.GetTasks = append(mock.calls.GetTasks, callInfo)
	mock.lockGetTasks.Unlock()
	return mock.GetTasksFunc(ctx, in)
}

// GetTasksCalls gets all the calls that were made to GetTasks.
// Check the length with:
//
//	len(mockedUsecase.GetTasksCalls())
func (mock *MockUsecase) GetTasksCalls() []struct {
	Ctx context.Context
	In  Input
} {
	var calls []struct {
		Ctx context.Context
		In  Input
	}
	mock.lockGetTasks.RLock()
	calls = mock.calls.GetTasks
	mock.lockGetTasks.RUnlock()
	return calls
}

// Ensure that MockPostgres does implement Postgres.
// If this is not the case, regenerate this file with mockery.
var _ Postgres = &MockPostgres{}

// MockPostgres is a mock implementation of Postgres.
//
//	func TestSomethingThatUsesPostgres(t *testing.T) {
//
//		// make and configure a mocked Postgres
//		mockedPostgres := &MockPostgres{
//			GetEquationsByIDsFunc: func(ctx context.Context, ids []uuid.UUID) ([]domain.Equation, error) {
//				panic("mock out the GetEquationsByIDs method")
//			},
//			GetTasksByIDsFunc: func(ctx context.Context, ids []uuid.UUID, userID uuid.UUID) ([]domain.Task, error) {
//				panic("mock out the GetTasksByIDs method")
//			},
//		}
//
//		// use mockedPostgres in code that requires Postgres
//		// and then make assertions.
//
//	}
type MockPostgres struct {
	// GetEquationsByIDsFunc mocks the GetEquationsByIDs method.
	GetEquationsByIDsFunc func(ctx context.Context, ids []uuid.UUID) ([]domain.Equation, error)

	// GetTasksByIDsFunc mocks the GetTasksByIDs method.
	GetTasksByIDsFunc func(ctx context.Context, ids []uuid.UUID, userID uuid.UUID) ([]domain.Task, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetEquationsByIDs holds details about calls to the GetEquationsByIDs method.
		GetEquationsByIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ids is the ids argument value.
			Ids []uuid.UUID
		}
		// GetTasksByIDs holds details about calls to the GetTasksByIDs method.
		GetTasksByIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ids is the ids argument value.
			Ids []uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
	}
	lockGetEquationsByIDs sync.RWMutex
	lockGetTasksByIDs     sync.RWMutex
}

// GetEquationsByIDs calls GetEquationsByIDsFunc.
func (mock *MockPostgres) GetEquationsByIDs(ctx context.Context, ids []uuid.UUID) ([]domain.Equation, error) {
	if mock.GetEquationsByIDsFunc == nil {
		panic("MockPostgres.GetEquationsByIDsFunc: method is nil but Postgres.GetEquationsByIDs was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ids []uuid.UUID
	}{
		Ctx: ctx,
		Ids: ids,
	}
	mock.lockGetEquationsByIDs.Lock()
	mock.calls.GetEquationsByIDs = append(mock.calls.GetEquationsByIDs, callInfo)
	mock.lockGetEquationsByIDs.Unlock()
	return mock.GetEquationsByIDsFunc(ctx, ids)
}

// GetEquationsByIDsCalls gets all the calls that were made to GetEquationsByIDs.
// Check the length with:
//
//	len(mockedPostgres.GetEquationsByIDsCalls())
func (mock *MockPostgres) GetEquationsByIDsCalls() []struct {
	Ctx context.Context
	Ids []uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		Ids []uuid.UUID
	}
	mock.lockGetEquationsByIDs.RLock()
	calls = mock.calls.GetEquationsByIDs
	mock.lockGetEquationsByIDs.RUnlock()
	return calls
}

// GetTasksByIDs calls GetTasksByIDsFunc.
func (mock *MockPostgres) GetTasksByIDs(ctx context.Context, ids []uuid.UUID, userID uuid.UUID) ([]domain.Task, error) {
	if mock.GetTasksByIDsFunc == nil {
		panic("MockPostgres.GetTasksByIDsFunc: method is nil but Postgres.GetTasksByIDs was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Ids    []uuid.UUID
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		Ids:    ids,
		UserID: userID,
	}
	mock.lockGetTasksByIDs.Lock()
	mock.calls.GetTasksByIDs = append(mock.calls.GetTasksByIDs, callInfo)
	mock.lockGetTasksByIDs.Unlock()
	return mock.GetTasksByIDsFunc(ctx, ids, userID)
}

// GetTasksByIDsCalls gets all the calls that were made to GetTasksByIDs.
// Check the length with:
//
//	len(mockedPostgres.GetTasksByIDsCalls())
func (mock *MockPostgres) GetTasksByIDsCalls() []struct {
	Ctx    context.Context
	Ids    []uuid.UUID
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		Ids    []uuid.UUID
		UserID uuid.UUID
	}
	mock.lockGetTasksByIDs.RLock()
	calls = mock.calls.GetTasksByIDs
	mock.lockGetTasksByIDs.RUnlock()
	return calls
}
