// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package refresh

import (
	"context"
	"pinnAutomizer/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgres creates a new instance of MockPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgres {
	mock := &MockPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgres is an autogenerated mock type for the Postgres type
type MockPostgres struct {
	mock.Mock
}

type MockPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgres) EXPECT() *MockPostgres_Expecter {
	return &MockPostgres_Expecter{mock: &_m.Mock}
}

// Refresh provides a mock function for the type MockPostgres
func (_mock *MockPostgres) Refresh(ctx context.Context, userID uuid.UUID, newAccessToken string) error {
	ret := _mock.Called(ctx, userID, newAccessToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, newAccessToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockPostgres_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - newAccessToken string
func (_e *MockPostgres_Expecter) Refresh(ctx interface{}, userID interface{}, newAccessToken interface{}) *MockPostgres_Refresh_Call {
	return &MockPostgres_Refresh_Call{Call: _e.mock.On("Refresh", ctx, userID, newAccessToken)}
}

func (_c *MockPostgres_Refresh_Call) Run(run func(ctx context.Context, userID uuid.UUID, newAccessToken string)) *MockPostgres_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostgres_Refresh_Call) Return(err error) *MockPostgres_Refresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_Refresh_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, newAccessToken string) error) *MockPostgres_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwtService creates a new instance of MockJwtService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwtService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwtService {
	mock := &MockJwtService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwtService is an autogenerated mock type for the JwtService type
type MockJwtService struct {
	mock.Mock
}

type MockJwtService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwtService) EXPECT() *MockJwtService_Expecter {
	return &MockJwtService_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockJwtService
func (_mock *MockJwtService) GenerateAccessToken(userID uuid.UUID) (domain.Token, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (domain.Token, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) domain.Token); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(domain.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwtService_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockJwtService_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockJwtService_Expecter) GenerateAccessToken(userID interface{}) *MockJwtService_GenerateAccessToken_Call {
	return &MockJwtService_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userID)}
}

func (_c *MockJwtService_GenerateAccessToken_Call) Run(run func(userID uuid.UUID)) *MockJwtService_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJwtService_GenerateAccessToken_Call) Return(token domain.Token, err error) *MockJwtService_GenerateAccessToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockJwtService_GenerateAccessToken_Call) RunAndReturn(run func(userID uuid.UUID) (domain.Token, error)) *MockJwtService_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function for the type MockJwtService
func (_mock *MockJwtService) ValidateRefreshToken(ctx context.Context, refreshToken string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwtService_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockJwtService_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockJwtService_Expecter) ValidateRefreshToken(ctx interface{}, refreshToken interface{}) *MockJwtService_ValidateRefreshToken_Call {
	return &MockJwtService_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", ctx, refreshToken)}
}

func (_c *MockJwtService_ValidateRefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockJwtService_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwtService_ValidateRefreshToken_Call) Return(uUID uuid.UUID, err error) *MockJwtService_ValidateRefreshToken_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockJwtService_ValidateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (uuid.UUID, error)) *MockJwtService_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
