// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package authLogout

import (
	"context"
	"sync"

	"github.com/AridanWarlock/pinnAutomizer/internal/domain"
	"github.com/google/uuid"
)

// Ensure that MockUsecase does implement Usecase.
// If this is not the case, regenerate this file with mockery.
var _ Usecase = &MockUsecase{}

// MockUsecase is a mock implementation of Usecase.
//
//	func TestSomethingThatUsesUsecase(t *testing.T) {
//
//		// make and configure a mocked Usecase
//		mockedUsecase := &MockUsecase{
//			LogoutFunc: func(ctx context.Context) error {
//				panic("mock out the Logout method")
//			},
//		}
//
//		// use mockedUsecase in code that requires Usecase
//		// and then make assertions.
//
//	}
type MockUsecase struct {
	// LogoutFunc mocks the Logout method.
	LogoutFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Logout holds details about calls to the Logout method.
		Logout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockLogout sync.RWMutex
}

// Logout calls LogoutFunc.
func (mock *MockUsecase) Logout(ctx context.Context) error {
	if mock.LogoutFunc == nil {
		panic("MockUsecase.LogoutFunc: method is nil but Usecase.Logout was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	return mock.LogoutFunc(ctx)
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//
//	len(mockedUsecase.LogoutCalls())
func (mock *MockUsecase) LogoutCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}

// Ensure that MockPostgres does implement Postgres.
// If this is not the case, regenerate this file with mockery.
var _ Postgres = &MockPostgres{}

// MockPostgres is a mock implementation of Postgres.
//
//	func TestSomethingThatUsesPostgres(t *testing.T) {
//
//		// make and configure a mocked Postgres
//		mockedPostgres := &MockPostgres{
//			LogoutFunc: func(ctx context.Context, userID uuid.UUID, fingerprint domain.Fingerprint) error {
//				panic("mock out the Logout method")
//			},
//		}
//
//		// use mockedPostgres in code that requires Postgres
//		// and then make assertions.
//
//	}
type MockPostgres struct {
	// LogoutFunc mocks the Logout method.
	LogoutFunc func(ctx context.Context, userID uuid.UUID, fingerprint domain.Fingerprint) error

	// calls tracks calls to the methods.
	calls struct {
		// Logout holds details about calls to the Logout method.
		Logout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Fingerprint is the fingerprint argument value.
			Fingerprint domain.Fingerprint
		}
	}
	lockLogout sync.RWMutex
}

// Logout calls LogoutFunc.
func (mock *MockPostgres) Logout(ctx context.Context, userID uuid.UUID, fingerprint domain.Fingerprint) error {
	if mock.LogoutFunc == nil {
		panic("MockPostgres.LogoutFunc: method is nil but Postgres.Logout was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		UserID      uuid.UUID
		Fingerprint domain.Fingerprint
	}{
		Ctx:         ctx,
		UserID:      userID,
		Fingerprint: fingerprint,
	}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	return mock.LogoutFunc(ctx, userID, fingerprint)
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//
//	len(mockedPostgres.LogoutCalls())
func (mock *MockPostgres) LogoutCalls() []struct {
	Ctx         context.Context
	UserID      uuid.UUID
	Fingerprint domain.Fingerprint
} {
	var calls []struct {
		Ctx         context.Context
		UserID      uuid.UUID
		Fingerprint domain.Fingerprint
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}

// Ensure that MockRedis does implement Redis.
// If this is not the case, regenerate this file with mockery.
var _ Redis = &MockRedis{}

// MockRedis is a mock implementation of Redis.
//
//	func TestSomethingThatUsesRedis(t *testing.T) {
//
//		// make and configure a mocked Redis
//		mockedRedis := &MockRedis{
//			DeleteFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Delete method")
//			},
//		}
//
//		// use mockedRedis in code that requires Redis
//		// and then make assertions.
//
//	}
type MockRedis struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, key string) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
	}
	lockDelete sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *MockRedis) Delete(ctx context.Context, key string) error {
	if mock.DeleteFunc == nil {
		panic("MockRedis.DeleteFunc: method is nil but Redis.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedRedis.DeleteCalls())
func (mock *MockRedis) DeleteCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}
