// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authLogout

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgres creates a new instance of MockPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgres {
	mock := &MockPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgres is an autogenerated mock type for the Postgres type
type MockPostgres struct {
	mock.Mock
}

type MockPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgres) EXPECT() *MockPostgres_Expecter {
	return &MockPostgres_Expecter{mock: &_m.Mock}
}

// Logout provides a mock function for the type MockPostgres
func (_mock *MockPostgres) Logout(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockPostgres_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPostgres_Expecter) Logout(ctx interface{}, userID interface{}) *MockPostgres_Logout_Call {
	return &MockPostgres_Logout_Call{Call: _e.mock.On("Logout", ctx, userID)}
}

func (_c *MockPostgres_Logout_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPostgres_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_Logout_Call) Return(err error) *MockPostgres_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_Logout_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockPostgres_Logout_Call {
	_c.Call.Return(run)
	return _c
}
