// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package authLogout

import (
	"context"
	"sync"

	"github.com/google/uuid"
)

// Ensure that MockUsecase does implement Usecase.
// If this is not the case, regenerate this file with mockery.
var _ Usecase = &MockUsecase{}

// MockUsecase is a mock implementation of Usecase.
//
//	func TestSomethingThatUsesUsecase(t *testing.T) {
//
//		// make and configure a mocked Usecase
//		mockedUsecase := &MockUsecase{
//			LogoutFunc: func(ctx context.Context, in Input) error {
//				panic("mock out the Logout method")
//			},
//		}
//
//		// use mockedUsecase in code that requires Usecase
//		// and then make assertions.
//
//	}
type MockUsecase struct {
	// LogoutFunc mocks the Logout method.
	LogoutFunc func(ctx context.Context, in Input) error

	// calls tracks calls to the methods.
	calls struct {
		// Logout holds details about calls to the Logout method.
		Logout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In Input
		}
	}
	lockLogout sync.RWMutex
}

// Logout calls LogoutFunc.
func (mock *MockUsecase) Logout(ctx context.Context, in Input) error {
	if mock.LogoutFunc == nil {
		panic("MockUsecase.LogoutFunc: method is nil but Usecase.Logout was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  Input
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	return mock.LogoutFunc(ctx, in)
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//
//	len(mockedUsecase.LogoutCalls())
func (mock *MockUsecase) LogoutCalls() []struct {
	Ctx context.Context
	In  Input
} {
	var calls []struct {
		Ctx context.Context
		In  Input
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}

// Ensure that MockPostgres does implement Postgres.
// If this is not the case, regenerate this file with mockery.
var _ Postgres = &MockPostgres{}

// MockPostgres is a mock implementation of Postgres.
//
//	func TestSomethingThatUsesPostgres(t *testing.T) {
//
//		// make and configure a mocked Postgres
//		mockedPostgres := &MockPostgres{
//			LogoutFunc: func(ctx context.Context, userID uuid.UUID) error {
//				panic("mock out the Logout method")
//			},
//		}
//
//		// use mockedPostgres in code that requires Postgres
//		// and then make assertions.
//
//	}
type MockPostgres struct {
	// LogoutFunc mocks the Logout method.
	LogoutFunc func(ctx context.Context, userID uuid.UUID) error

	// calls tracks calls to the methods.
	calls struct {
		// Logout holds details about calls to the Logout method.
		Logout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
	}
	lockLogout sync.RWMutex
}

// Logout calls LogoutFunc.
func (mock *MockPostgres) Logout(ctx context.Context, userID uuid.UUID) error {
	if mock.LogoutFunc == nil {
		panic("MockPostgres.LogoutFunc: method is nil but Postgres.Logout was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	return mock.LogoutFunc(ctx, userID)
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//
//	len(mockedPostgres.LogoutCalls())
func (mock *MockPostgres) LogoutCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}
